// Code generated by Fern. DO NOT EDIT.

package wallets

import (
	context "context"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	core "github.com/MKT-AGI/mkt-sdk-go/core"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Get the details of a wallet transfer by transfer number.
func (c *Client) GetTransferDetail(
	ctx context.Context,
	request *mktsdkgo.GetAPIV1PaymentWalletTransfersTransferNoRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferV2Response, error) {
	response, err := c.WithRawResponse.GetTransferDetail(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// List all wallets for the current authenticated user.
func (c *Client) ListWallets(
	ctx context.Context,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultArrayInternalPaymentsInternalWebWalletV2Response, error) {
	response, err := c.WithRawResponse.ListWallets(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get a single wallet by ID with ownership verification.
func (c *Client) GetWallet(
	ctx context.Context,
	request *mktsdkgo.GetAPIV1PaymentWalletsIDRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletV2Response, error) {
	response, err := c.WithRawResponse.GetWallet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Convert all balance from the source wallet to a target-currency wallet in-place, applying the exchange rate with markup. Idempotent via idempotency_key.
func (c *Client) ConvertWalletCurrency(
	ctx context.Context,
	request *mktsdkgo.PostAPIV1PaymentWalletsIDConvertCurrencyRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.ConvertWalletCurrency(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// List paginated transactions for a specific wallet.
func (c *Client) ListWalletTransactions(
	ctx context.Context,
	request *mktsdkgo.GetAPIV1PaymentWalletsIDTransactionsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.ListWalletTransactions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Transfer funds from the source wallet to another wallet belonging to the same user.
func (c *Client) TransferBetweenWallets(
	ctx context.Context,
	request *mktsdkgo.PostAPIV1PaymentWalletsIDTransferRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope, error) {
	response, err := c.WithRawResponse.TransferBetweenWallets(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Transfer all balance from a revenue wallet to the user's main wallet. Only revenue wallets are eligible.
func (c *Client) TransferRevenueWalletBalanceToMainWallet(
	ctx context.Context,
	request *mktsdkgo.PostAPIV1PaymentWalletsIDTransferToMainRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope, error) {
	response, err := c.WithRawResponse.TransferRevenueWalletBalanceToMainWallet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
