// Code generated by Fern. DO NOT EDIT.

package accounts

import (
	context "context"

	core "github.com/MKT-AGI/mkt-sdk-go/core"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Handle incoming GitHub webhook events (installation, push, etc.)
func (c *Client) ReceiveGitHubWebhookEvents(
	ctx context.Context,
	request map[string]any,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.ReceiveGitHubWebhookEvents(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
