// Code generated by Fern. DO NOT EDIT.

package usersecrets

import (
	context "context"
	http "net/http"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	core "github.com/MKT-AGI/mkt-sdk-go/core"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListUserSecrets(
	ctx context.Context,
	request *mktsdkgo.GetSecretsUserIDRequest,
	opts ...option.RequestOption,
) (*core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/secrets/%v",
		request.UserID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetUserSecret(
	ctx context.Context,
	request *mktsdkgo.GetSecretsUserIDKeyRequest,
	opts ...option.RequestOption,
) (*core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/secrets/%v/%v",
		request.UserID,
		request.Key,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateOrUpdateUserSecret(
	ctx context.Context,
	request *mktsdkgo.PutSecretsUserIDKeyRequest,
	opts ...option.RequestOption,
) (*core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/secrets/%v/%v",
		request.UserID,
		request.Key,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteUserSecret(
	ctx context.Context,
	request *mktsdkgo.DeleteSecretsUserIDKeyRequest,
	opts ...option.RequestOption,
) (*core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/secrets/%v/%v",
		request.UserID,
		request.Key,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
