// Code generated by Fern. DO NOT EDIT.

package user_routes_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	client "github.com/MKT-AGI/mkt-sdk-go/client"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestUserRoutesListUserModelRoutesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.GetGatewayUserIDRoutesRequest{
		UserID: 1,
	}
	_, invocationErr := client.UserRoutes.ListUserModelRoutes(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestUserRoutesListUserModelRoutesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestUserRoutesListUserModelRoutesWithWireMock", "GET", "/gateway/1/routes", nil, 1)
}

func TestUserRoutesCreateUserModelRouteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.PostGatewayUserIDRoutesRequest{
		UserID: 1,
		Body: &mktsdkgo.PostGatewayUserIDRoutesRequestBody{
			StringUnknownMap: map[string]any{
				"key": "value",
			},
		},
	}
	_, invocationErr := client.UserRoutes.CreateUserModelRoute(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestUserRoutesCreateUserModelRouteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestUserRoutesCreateUserModelRouteWithWireMock", "POST", "/gateway/1/routes", nil, 1)
}

func TestUserRoutesGetUserModelRouteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.GetGatewayUserIDRoutesIDRequest{
		UserID: 1,
		ID:     1,
	}
	_, invocationErr := client.UserRoutes.GetUserModelRoute(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestUserRoutesGetUserModelRouteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestUserRoutesGetUserModelRouteWithWireMock", "GET", "/gateway/1/routes/1", nil, 1)
}

func TestUserRoutesDeleteUserModelRouteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.DeleteGatewayUserIDRoutesIDRequest{
		UserID: 1,
		ID:     1,
	}
	_, invocationErr := client.UserRoutes.DeleteUserModelRoute(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestUserRoutesDeleteUserModelRouteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestUserRoutesDeleteUserModelRouteWithWireMock", "DELETE", "/gateway/1/routes/1", nil, 1)
}

func TestUserRoutesListRouteVisibilityFiltersWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.GetGatewayUserIDRoutesIDFiltersRequest{
		UserID: 1,
		ID:     1,
	}
	_, invocationErr := client.UserRoutes.ListRouteVisibilityFilters(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestUserRoutesListRouteVisibilityFiltersWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestUserRoutesListRouteVisibilityFiltersWithWireMock", "GET", "/gateway/1/routes/1/filters", nil, 1)
}

func TestUserRoutesAddRouteVisibilityFilterWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.PostGatewayUserIDRoutesIDFiltersRequest{
		UserID: 1,
		ID:     1,
		Body: &mktsdkgo.PostGatewayUserIDRoutesIDFiltersRequestBody{
			StringUnknownMap: map[string]any{
				"key": "value",
			},
		},
	}
	_, invocationErr := client.UserRoutes.AddRouteVisibilityFilter(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestUserRoutesAddRouteVisibilityFilterWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestUserRoutesAddRouteVisibilityFilterWithWireMock", "POST", "/gateway/1/routes/1/filters", nil, 1)
}

func TestUserRoutesRemoveRouteVisibilityFilterWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.DeleteGatewayUserIDRoutesIDFiltersTargetUserIDRequest{
		UserID:       1,
		ID:           1,
		TargetUserID: 1,
	}
	_, invocationErr := client.UserRoutes.RemoveRouteVisibilityFilter(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestUserRoutesRemoveRouteVisibilityFilterWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestUserRoutesRemoveRouteVisibilityFilterWithWireMock", "DELETE", "/gateway/1/routes/1/filters/1", nil, 1)
}
