// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	big "math/big"
)

var (
	anthropicErrorDetailFieldMessage = big.NewInt(1 << 0)
	anthropicErrorDetailFieldType    = big.NewInt(1 << 1)
)

type AnthropicErrorDetail struct {
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	Type    *string `json:"type,omitempty" url:"type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AnthropicErrorDetail) GetMessage() *string {
	if a == nil {
		return nil
	}
	return a.Message
}

func (a *AnthropicErrorDetail) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *AnthropicErrorDetail) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AnthropicErrorDetail) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnthropicErrorDetail) SetMessage(message *string) {
	a.Message = message
	a.require(anthropicErrorDetailFieldMessage)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AnthropicErrorDetail) SetType(type_ *string) {
	a.Type = type_
	a.require(anthropicErrorDetailFieldType)
}

func (a *AnthropicErrorDetail) UnmarshalJSON(data []byte) error {
	type unmarshaler AnthropicErrorDetail
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AnthropicErrorDetail(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AnthropicErrorDetail) MarshalJSON() ([]byte, error) {
	type embed AnthropicErrorDetail
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AnthropicErrorDetail) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	githubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponseFieldError = big.NewInt(1 << 0)
	githubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponseFieldType  = big.NewInt(1 << 1)
)

type GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse struct {
	Error *AnthropicErrorDetail `json:"error,omitempty" url:"error,omitempty"`
	Type  *string               `json:"type,omitempty" url:"type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse) GetError() *AnthropicErrorDetail {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse) GetType() *string {
	if g == nil {
		return nil
	}
	return g.Type
}

func (g *GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse) SetError(error_ *AnthropicErrorDetail) {
	g.Error = error_
	g.require(githubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponseFieldError)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse) SetType(type_ *string) {
	g.Type = type_
	g.require(githubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponseFieldType)
}

func (g *GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse) MarshalJSON() ([]byte, error) {
	type embed GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Preferences is the user's preference object (lang, theme, ...).
var (
	githubComMktAgiAixInternalAccountsInternalDomainUserPreferencesFieldLang  = big.NewInt(1 << 0)
	githubComMktAgiAixInternalAccountsInternalDomainUserPreferencesFieldTheme = big.NewInt(1 << 1)
)

type GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences struct {
	// BCP 47, e.g. "zh-CN"
	Lang *string `json:"lang,omitempty" url:"lang,omitempty"`
	// "light" | "dark"
	Theme *string `json:"theme,omitempty" url:"theme,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences) GetLang() *string {
	if g == nil {
		return nil
	}
	return g.Lang
}

func (g *GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences) GetTheme() *string {
	if g == nil {
		return nil
	}
	return g.Theme
}

func (g *GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetLang sets the Lang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences) SetLang(lang *string) {
	g.Lang = lang
	g.require(githubComMktAgiAixInternalAccountsInternalDomainUserPreferencesFieldLang)
}

// SetTheme sets the Theme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences) SetTheme(theme *string) {
	g.Theme = theme
	g.require(githubComMktAgiAixInternalAccountsInternalDomainUserPreferencesFieldTheme)
}

func (g *GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldBody        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldCategory    = big.NewInt(1 << 1)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldCreatedAt   = big.NewInt(1 << 2)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldCreatedBy   = big.NewInt(1 << 3)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldExpiresAt   = big.NewInt(1 << 4)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldID          = big.NewInt(1 << 5)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldParentID    = big.NewInt(1 << 6)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldPublishedAt = big.NewInt(1 << 7)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldSection     = big.NewInt(1 << 8)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldSortOrder   = big.NewInt(1 << 9)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldStatus      = big.NewInt(1 << 10)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldSummary     = big.NewInt(1 << 11)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldTitle       = big.NewInt(1 << 12)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldType        = big.NewInt(1 << 13)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldUpdatedAt   = big.NewInt(1 << 14)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldUpdatedBy   = big.NewInt(1 << 15)
	githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldVersion     = big.NewInt(1 << 16)
)

type GithubComMktAgiAixInternalBulletinInternalDomainBulletin struct {
	Body        *string `json:"body,omitempty" url:"body,omitempty"`
	Category    *string `json:"category,omitempty" url:"category,omitempty"`
	CreatedAt   *int    `json:"created_at,omitempty" url:"created_at,omitempty"`
	CreatedBy   *int    `json:"created_by,omitempty" url:"created_by,omitempty"`
	ExpiresAt   *int    `json:"expires_at,omitempty" url:"expires_at,omitempty"`
	ID          *int    `json:"id,omitempty" url:"id,omitempty"`
	ParentID    *int    `json:"parent_id,omitempty" url:"parent_id,omitempty"`
	PublishedAt *int    `json:"published_at,omitempty" url:"published_at,omitempty"`
	Section     *string `json:"section,omitempty" url:"section,omitempty"`
	SortOrder   *int    `json:"sort_order,omitempty" url:"sort_order,omitempty"`
	Status      *string `json:"status,omitempty" url:"status,omitempty"`
	Summary     *string `json:"summary,omitempty" url:"summary,omitempty"`
	Title       *string `json:"title,omitempty" url:"title,omitempty"`
	Type        *string `json:"type,omitempty" url:"type,omitempty"`
	UpdatedAt   *int    `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	UpdatedBy   *int    `json:"updated_by,omitempty" url:"updated_by,omitempty"`
	Version     *string `json:"version,omitempty" url:"version,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetBody() *string {
	if g == nil {
		return nil
	}
	return g.Body
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetCategory() *string {
	if g == nil {
		return nil
	}
	return g.Category
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetCreatedAt() *int {
	if g == nil {
		return nil
	}
	return g.CreatedAt
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetCreatedBy() *int {
	if g == nil {
		return nil
	}
	return g.CreatedBy
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetExpiresAt() *int {
	if g == nil {
		return nil
	}
	return g.ExpiresAt
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetID() *int {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetParentID() *int {
	if g == nil {
		return nil
	}
	return g.ParentID
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetPublishedAt() *int {
	if g == nil {
		return nil
	}
	return g.PublishedAt
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetSection() *string {
	if g == nil {
		return nil
	}
	return g.Section
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetSortOrder() *int {
	if g == nil {
		return nil
	}
	return g.SortOrder
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetStatus() *string {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetSummary() *string {
	if g == nil {
		return nil
	}
	return g.Summary
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetTitle() *string {
	if g == nil {
		return nil
	}
	return g.Title
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetType() *string {
	if g == nil {
		return nil
	}
	return g.Type
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetUpdatedAt() *int {
	if g == nil {
		return nil
	}
	return g.UpdatedAt
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetUpdatedBy() *int {
	if g == nil {
		return nil
	}
	return g.UpdatedBy
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetVersion() *string {
	if g == nil {
		return nil
	}
	return g.Version
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetBody sets the Body field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetBody(body *string) {
	g.Body = body
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldBody)
}

// SetCategory sets the Category field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetCategory(category *string) {
	g.Category = category
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldCategory)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetCreatedAt(createdAt *int) {
	g.CreatedAt = createdAt
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldCreatedAt)
}

// SetCreatedBy sets the CreatedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetCreatedBy(createdBy *int) {
	g.CreatedBy = createdBy
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldCreatedBy)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetExpiresAt(expiresAt *int) {
	g.ExpiresAt = expiresAt
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldExpiresAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetID(id *int) {
	g.ID = id
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldID)
}

// SetParentID sets the ParentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetParentID(parentID *int) {
	g.ParentID = parentID
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldParentID)
}

// SetPublishedAt sets the PublishedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetPublishedAt(publishedAt *int) {
	g.PublishedAt = publishedAt
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldPublishedAt)
}

// SetSection sets the Section field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetSection(section *string) {
	g.Section = section
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldSection)
}

// SetSortOrder sets the SortOrder field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetSortOrder(sortOrder *int) {
	g.SortOrder = sortOrder
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldSortOrder)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetStatus(status *string) {
	g.Status = status
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldStatus)
}

// SetSummary sets the Summary field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetSummary(summary *string) {
	g.Summary = summary
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldSummary)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetTitle(title *string) {
	g.Title = title
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldTitle)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetType(type_ *string) {
	g.Type = type_
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldType)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetUpdatedAt(updatedAt *int) {
	g.UpdatedAt = updatedAt
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldUpdatedAt)
}

// SetUpdatedBy sets the UpdatedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetUpdatedBy(updatedBy *int) {
	g.UpdatedBy = updatedBy
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldUpdatedBy)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetVersion(version *string) {
	g.Version = version
	g.require(githubComMktAgiAixInternalBulletinInternalDomainBulletinFieldVersion)
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalBulletinInternalDomainBulletin
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalBulletinInternalDomainBulletin(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalBulletinInternalDomainBulletin
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubComMktAgiAixInternalIamAccessGrantFieldCreatedAt = big.NewInt(1 << 0)
	githubComMktAgiAixInternalIamAccessGrantFieldCreatedBy = big.NewInt(1 << 1)
	githubComMktAgiAixInternalIamAccessGrantFieldExpiresAt = big.NewInt(1 << 2)
	githubComMktAgiAixInternalIamAccessGrantFieldOrderNo   = big.NewInt(1 << 3)
	githubComMktAgiAixInternalIamAccessGrantFieldSource    = big.NewInt(1 << 4)
	githubComMktAgiAixInternalIamAccessGrantFieldUserID    = big.NewInt(1 << 5)
)

type GithubComMktAgiAixInternalIamAccessGrant struct {
	CreatedAt *int    `json:"createdAt,omitempty" url:"createdAt,omitempty"`
	CreatedBy *int    `json:"createdBy,omitempty" url:"createdBy,omitempty"`
	ExpiresAt *int    `json:"expiresAt,omitempty" url:"expiresAt,omitempty"`
	OrderNo   *string `json:"orderNo,omitempty" url:"orderNo,omitempty"`
	// "grant" | "purchase"
	Source *string `json:"source,omitempty" url:"source,omitempty"`
	UserID *int    `json:"userID,omitempty" url:"userID,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalIamAccessGrant) GetCreatedAt() *int {
	if g == nil {
		return nil
	}
	return g.CreatedAt
}

func (g *GithubComMktAgiAixInternalIamAccessGrant) GetCreatedBy() *int {
	if g == nil {
		return nil
	}
	return g.CreatedBy
}

func (g *GithubComMktAgiAixInternalIamAccessGrant) GetExpiresAt() *int {
	if g == nil {
		return nil
	}
	return g.ExpiresAt
}

func (g *GithubComMktAgiAixInternalIamAccessGrant) GetOrderNo() *string {
	if g == nil {
		return nil
	}
	return g.OrderNo
}

func (g *GithubComMktAgiAixInternalIamAccessGrant) GetSource() *string {
	if g == nil {
		return nil
	}
	return g.Source
}

func (g *GithubComMktAgiAixInternalIamAccessGrant) GetUserID() *int {
	if g == nil {
		return nil
	}
	return g.UserID
}

func (g *GithubComMktAgiAixInternalIamAccessGrant) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalIamAccessGrant) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalIamAccessGrant) SetCreatedAt(createdAt *int) {
	g.CreatedAt = createdAt
	g.require(githubComMktAgiAixInternalIamAccessGrantFieldCreatedAt)
}

// SetCreatedBy sets the CreatedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalIamAccessGrant) SetCreatedBy(createdBy *int) {
	g.CreatedBy = createdBy
	g.require(githubComMktAgiAixInternalIamAccessGrantFieldCreatedBy)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalIamAccessGrant) SetExpiresAt(expiresAt *int) {
	g.ExpiresAt = expiresAt
	g.require(githubComMktAgiAixInternalIamAccessGrantFieldExpiresAt)
}

// SetOrderNo sets the OrderNo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalIamAccessGrant) SetOrderNo(orderNo *string) {
	g.OrderNo = orderNo
	g.require(githubComMktAgiAixInternalIamAccessGrantFieldOrderNo)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalIamAccessGrant) SetSource(source *string) {
	g.Source = source
	g.require(githubComMktAgiAixInternalIamAccessGrantFieldSource)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalIamAccessGrant) SetUserID(userID *int) {
	g.UserID = userID
	g.require(githubComMktAgiAixInternalIamAccessGrantFieldUserID)
}

func (g *GithubComMktAgiAixInternalIamAccessGrant) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalIamAccessGrant
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalIamAccessGrant(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalIamAccessGrant) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalIamAccessGrant
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalIamAccessGrant) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubComMktAgiAixInternalPkgGinxCodeRespFieldCode        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalPkgGinxCodeRespFieldData        = big.NewInt(1 << 1)
	githubComMktAgiAixInternalPkgGinxCodeRespFieldLimit       = big.NewInt(1 << 2)
	githubComMktAgiAixInternalPkgGinxCodeRespFieldMessage     = big.NewInt(1 << 3)
	githubComMktAgiAixInternalPkgGinxCodeRespFieldPage        = big.NewInt(1 << 4)
	githubComMktAgiAixInternalPkgGinxCodeRespFieldTotal       = big.NewInt(1 << 5)
	githubComMktAgiAixInternalPkgGinxCodeRespFieldUserMessage = big.NewInt(1 << 6)
)

type GithubComMktAgiAixInternalPkgGinxCodeResp struct {
	Code        *int    `json:"code,omitempty" url:"code,omitempty"`
	Data        any     `json:"data,omitempty" url:"data,omitempty"`
	Limit       *int    `json:"limit,omitempty" url:"limit,omitempty"`
	Message     *string `json:"message,omitempty" url:"message,omitempty"`
	Page        *int    `json:"page,omitempty" url:"page,omitempty"`
	Total       *int    `json:"total,omitempty" url:"total,omitempty"`
	UserMessage *string `json:"user_message,omitempty" url:"user_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) GetData() any {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) GetPage() *int {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) GetUserMessage() *string {
	if g == nil {
		return nil
	}
	return g.UserMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) SetCode(code *int) {
	g.Code = code
	g.require(githubComMktAgiAixInternalPkgGinxCodeRespFieldCode)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) SetData(data any) {
	g.Data = data
	g.require(githubComMktAgiAixInternalPkgGinxCodeRespFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) SetLimit(limit *int) {
	g.Limit = limit
	g.require(githubComMktAgiAixInternalPkgGinxCodeRespFieldLimit)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) SetMessage(message *string) {
	g.Message = message
	g.require(githubComMktAgiAixInternalPkgGinxCodeRespFieldMessage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) SetPage(page *int) {
	g.Page = page
	g.require(githubComMktAgiAixInternalPkgGinxCodeRespFieldPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) SetTotal(total *int) {
	g.Total = total
	g.require(githubComMktAgiAixInternalPkgGinxCodeRespFieldTotal)
}

// SetUserMessage sets the UserMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) SetUserMessage(userMessage *string) {
	g.UserMessage = userMessage
	g.require(githubComMktAgiAixInternalPkgGinxCodeRespFieldUserMessage)
}

func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalPkgGinxCodeResp
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalPkgGinxCodeResp(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalPkgGinxCodeResp
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalPkgGinxCodeResp) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubComMktAgiAixInternalPkgGinxResultAnyFieldCode        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalPkgGinxResultAnyFieldData        = big.NewInt(1 << 1)
	githubComMktAgiAixInternalPkgGinxResultAnyFieldLimit       = big.NewInt(1 << 2)
	githubComMktAgiAixInternalPkgGinxResultAnyFieldMessage     = big.NewInt(1 << 3)
	githubComMktAgiAixInternalPkgGinxResultAnyFieldPage        = big.NewInt(1 << 4)
	githubComMktAgiAixInternalPkgGinxResultAnyFieldTotal       = big.NewInt(1 << 5)
	githubComMktAgiAixInternalPkgGinxResultAnyFieldUserMessage = big.NewInt(1 << 6)
)

type GithubComMktAgiAixInternalPkgGinxResultAny struct {
	Code        *int    `json:"code,omitempty" url:"code,omitempty"`
	Data        any     `json:"data,omitempty" url:"data,omitempty"`
	Limit       *int    `json:"limit,omitempty" url:"limit,omitempty"`
	Message     *string `json:"message,omitempty" url:"message,omitempty"`
	Page        *int    `json:"page,omitempty" url:"page,omitempty"`
	Total       *int    `json:"total,omitempty" url:"total,omitempty"`
	UserMessage *string `json:"user_message,omitempty" url:"user_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultAny) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GithubComMktAgiAixInternalPkgGinxResultAny) GetData() any {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubComMktAgiAixInternalPkgGinxResultAny) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GithubComMktAgiAixInternalPkgGinxResultAny) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GithubComMktAgiAixInternalPkgGinxResultAny) GetPage() *int {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GithubComMktAgiAixInternalPkgGinxResultAny) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GithubComMktAgiAixInternalPkgGinxResultAny) GetUserMessage() *string {
	if g == nil {
		return nil
	}
	return g.UserMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultAny) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalPkgGinxResultAny) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultAny) SetCode(code *int) {
	g.Code = code
	g.require(githubComMktAgiAixInternalPkgGinxResultAnyFieldCode)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultAny) SetData(data any) {
	g.Data = data
	g.require(githubComMktAgiAixInternalPkgGinxResultAnyFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultAny) SetLimit(limit *int) {
	g.Limit = limit
	g.require(githubComMktAgiAixInternalPkgGinxResultAnyFieldLimit)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultAny) SetMessage(message *string) {
	g.Message = message
	g.require(githubComMktAgiAixInternalPkgGinxResultAnyFieldMessage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultAny) SetPage(page *int) {
	g.Page = page
	g.require(githubComMktAgiAixInternalPkgGinxResultAnyFieldPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultAny) SetTotal(total *int) {
	g.Total = total
	g.require(githubComMktAgiAixInternalPkgGinxResultAnyFieldTotal)
}

// SetUserMessage sets the UserMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultAny) SetUserMessage(userMessage *string) {
	g.UserMessage = userMessage
	g.require(githubComMktAgiAixInternalPkgGinxResultAnyFieldUserMessage)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultAny) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalPkgGinxResultAny
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalPkgGinxResultAny(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalPkgGinxResultAny) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalPkgGinxResultAny
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultAny) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldCode        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldData        = big.NewInt(1 << 1)
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldLimit       = big.NewInt(1 << 2)
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldMessage     = big.NewInt(1 << 3)
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldPage        = big.NewInt(1 << 4)
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldTotal       = big.NewInt(1 << 5)
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldUserMessage = big.NewInt(1 << 6)
)

type GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin struct {
	Code        *int                                                        `json:"code,omitempty" url:"code,omitempty"`
	Data        []*GithubComMktAgiAixInternalBulletinInternalDomainBulletin `json:"data,omitempty" url:"data,omitempty"`
	Limit       *int                                                        `json:"limit,omitempty" url:"limit,omitempty"`
	Message     *string                                                     `json:"message,omitempty" url:"message,omitempty"`
	Page        *int                                                        `json:"page,omitempty" url:"page,omitempty"`
	Total       *int                                                        `json:"total,omitempty" url:"total,omitempty"`
	UserMessage *string                                                     `json:"user_message,omitempty" url:"user_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetData() []*GithubComMktAgiAixInternalBulletinInternalDomainBulletin {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetPage() *int {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetUserMessage() *string {
	if g == nil {
		return nil
	}
	return g.UserMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetCode(code *int) {
	g.Code = code
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldCode)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetData(data []*GithubComMktAgiAixInternalBulletinInternalDomainBulletin) {
	g.Data = data
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetLimit(limit *int) {
	g.Limit = limit
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldLimit)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetMessage(message *string) {
	g.Message = message
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldMessage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetPage(page *int) {
	g.Page = page
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetTotal(total *int) {
	g.Total = total
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldTotal)
}

// SetUserMessage sets the UserMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetUserMessage(userMessage *string) {
	g.UserMessage = userMessage
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldUserMessage)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalBulletinInternalDomainBulletin) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldCode        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldData        = big.NewInt(1 << 1)
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldLimit       = big.NewInt(1 << 2)
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldMessage     = big.NewInt(1 << 3)
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldPage        = big.NewInt(1 << 4)
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldTotal       = big.NewInt(1 << 5)
	githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldUserMessage = big.NewInt(1 << 6)
)

type GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant struct {
	Code        *int                                        `json:"code,omitempty" url:"code,omitempty"`
	Data        []*GithubComMktAgiAixInternalIamAccessGrant `json:"data,omitempty" url:"data,omitempty"`
	Limit       *int                                        `json:"limit,omitempty" url:"limit,omitempty"`
	Message     *string                                     `json:"message,omitempty" url:"message,omitempty"`
	Page        *int                                        `json:"page,omitempty" url:"page,omitempty"`
	Total       *int                                        `json:"total,omitempty" url:"total,omitempty"`
	UserMessage *string                                     `json:"user_message,omitempty" url:"user_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) GetData() []*GithubComMktAgiAixInternalIamAccessGrant {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) GetPage() *int {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) GetUserMessage() *string {
	if g == nil {
		return nil
	}
	return g.UserMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) SetCode(code *int) {
	g.Code = code
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldCode)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) SetData(data []*GithubComMktAgiAixInternalIamAccessGrant) {
	g.Data = data
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) SetLimit(limit *int) {
	g.Limit = limit
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldLimit)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) SetMessage(message *string) {
	g.Message = message
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldMessage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) SetPage(page *int) {
	g.Page = page
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) SetTotal(total *int) {
	g.Total = total
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldTotal)
}

// SetUserMessage sets the UserMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) SetUserMessage(userMessage *string) {
	g.UserMessage = userMessage
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrantFieldUserMessage)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldCode        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldData        = big.NewInt(1 << 1)
	githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldLimit       = big.NewInt(1 << 2)
	githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldMessage     = big.NewInt(1 << 3)
	githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldPage        = big.NewInt(1 << 4)
	githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldTotal       = big.NewInt(1 << 5)
	githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldUserMessage = big.NewInt(1 << 6)
)

type GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin struct {
	Code        *int                                                      `json:"code,omitempty" url:"code,omitempty"`
	Data        *GithubComMktAgiAixInternalBulletinInternalDomainBulletin `json:"data,omitempty" url:"data,omitempty"`
	Limit       *int                                                      `json:"limit,omitempty" url:"limit,omitempty"`
	Message     *string                                                   `json:"message,omitempty" url:"message,omitempty"`
	Page        *int                                                      `json:"page,omitempty" url:"page,omitempty"`
	Total       *int                                                      `json:"total,omitempty" url:"total,omitempty"`
	UserMessage *string                                                   `json:"user_message,omitempty" url:"user_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetData() *GithubComMktAgiAixInternalBulletinInternalDomainBulletin {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetPage() *int {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetUserMessage() *string {
	if g == nil {
		return nil
	}
	return g.UserMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetCode(code *int) {
	g.Code = code
	g.require(githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldCode)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetData(data *GithubComMktAgiAixInternalBulletinInternalDomainBulletin) {
	g.Data = data
	g.require(githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetLimit(limit *int) {
	g.Limit = limit
	g.require(githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldLimit)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetMessage(message *string) {
	g.Message = message
	g.require(githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldMessage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetPage(page *int) {
	g.Page = page
	g.require(githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetTotal(total *int) {
	g.Total = total
	g.require(githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldTotal)
}

// SetUserMessage sets the UserMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) SetUserMessage(userMessage *string) {
	g.UserMessage = userMessage
	g.require(githubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletinFieldUserMessage)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalBulletinInternalDomainBulletin) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldCode        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldData        = big.NewInt(1 << 1)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldLimit       = big.NewInt(1 << 2)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldMessage     = big.NewInt(1 << 3)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldPage        = big.NewInt(1 << 4)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldTotal       = big.NewInt(1 << 5)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldUserMessage = big.NewInt(1 << 6)
)

type GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse struct {
	Code        *int                                             `json:"code,omitempty" url:"code,omitempty"`
	Data        *InternalAccountsInternalWebPasswordAuthResponse `json:"data,omitempty" url:"data,omitempty"`
	Limit       *int                                             `json:"limit,omitempty" url:"limit,omitempty"`
	Message     *string                                          `json:"message,omitempty" url:"message,omitempty"`
	Page        *int                                             `json:"page,omitempty" url:"page,omitempty"`
	Total       *int                                             `json:"total,omitempty" url:"total,omitempty"`
	UserMessage *string                                          `json:"user_message,omitempty" url:"user_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) GetData() *InternalAccountsInternalWebPasswordAuthResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) GetPage() *int {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) GetUserMessage() *string {
	if g == nil {
		return nil
	}
	return g.UserMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) SetCode(code *int) {
	g.Code = code
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldCode)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) SetData(data *InternalAccountsInternalWebPasswordAuthResponse) {
	g.Data = data
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) SetLimit(limit *int) {
	g.Limit = limit
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldLimit)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) SetMessage(message *string) {
	g.Message = message
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldMessage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) SetPage(page *int) {
	g.Page = page
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) SetTotal(total *int) {
	g.Total = total
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldTotal)
}

// SetUserMessage sets the UserMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) SetUserMessage(userMessage *string) {
	g.UserMessage = userMessage
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponseFieldUserMessage)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldCode        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldData        = big.NewInt(1 << 1)
	githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldLimit       = big.NewInt(1 << 2)
	githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldMessage     = big.NewInt(1 << 3)
	githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldPage        = big.NewInt(1 << 4)
	githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldTotal       = big.NewInt(1 << 5)
	githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldUserMessage = big.NewInt(1 << 6)
)

type GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo struct {
	Code        *int                                     `json:"code,omitempty" url:"code,omitempty"`
	Data        *InternalWisdomInternalWebWisdomDeleteVo `json:"data,omitempty" url:"data,omitempty"`
	Limit       *int                                     `json:"limit,omitempty" url:"limit,omitempty"`
	Message     *string                                  `json:"message,omitempty" url:"message,omitempty"`
	Page        *int                                     `json:"page,omitempty" url:"page,omitempty"`
	Total       *int                                     `json:"total,omitempty" url:"total,omitempty"`
	UserMessage *string                                  `json:"user_message,omitempty" url:"user_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) GetData() *InternalWisdomInternalWebWisdomDeleteVo {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) GetPage() *int {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) GetUserMessage() *string {
	if g == nil {
		return nil
	}
	return g.UserMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) SetCode(code *int) {
	g.Code = code
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldCode)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) SetData(data *InternalWisdomInternalWebWisdomDeleteVo) {
	g.Data = data
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) SetLimit(limit *int) {
	g.Limit = limit
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldLimit)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) SetMessage(message *string) {
	g.Message = message
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldMessage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) SetPage(page *int) {
	g.Page = page
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) SetTotal(total *int) {
	g.Total = total
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldTotal)
}

// SetUserMessage sets the UserMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) SetUserMessage(userMessage *string) {
	g.UserMessage = userMessage
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVoFieldUserMessage)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Authenticated user info and new-user flag for password auth.
var (
	internalAccountsInternalWebPasswordAuthResponseFieldIsNewUser = big.NewInt(1 << 0)
	internalAccountsInternalWebPasswordAuthResponseFieldUser      = big.NewInt(1 << 1)
)

type InternalAccountsInternalWebPasswordAuthResponse struct {
	// IsNewUser indicates whether a new account was created (true for register, false for login/reset).
	IsNewUser *bool `json:"is_new_user,omitempty" url:"is_new_user,omitempty"`
	// User is the authenticated user object.
	User any `json:"user,omitempty" url:"user,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InternalAccountsInternalWebPasswordAuthResponse) GetIsNewUser() *bool {
	if i == nil {
		return nil
	}
	return i.IsNewUser
}

func (i *InternalAccountsInternalWebPasswordAuthResponse) GetUser() any {
	if i == nil {
		return nil
	}
	return i.User
}

func (i *InternalAccountsInternalWebPasswordAuthResponse) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InternalAccountsInternalWebPasswordAuthResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetIsNewUser sets the IsNewUser field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebPasswordAuthResponse) SetIsNewUser(isNewUser *bool) {
	i.IsNewUser = isNewUser
	i.require(internalAccountsInternalWebPasswordAuthResponseFieldIsNewUser)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebPasswordAuthResponse) SetUser(user any) {
	i.User = user
	i.require(internalAccountsInternalWebPasswordAuthResponseFieldUser)
}

func (i *InternalAccountsInternalWebPasswordAuthResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler InternalAccountsInternalWebPasswordAuthResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InternalAccountsInternalWebPasswordAuthResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InternalAccountsInternalWebPasswordAuthResponse) MarshalJSON() ([]byte, error) {
	type embed InternalAccountsInternalWebPasswordAuthResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InternalAccountsInternalWebPasswordAuthResponse) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	internalAccountsInternalWebSetupRequestFieldEmail       = big.NewInt(1 << 0)
	internalAccountsInternalWebSetupRequestFieldName        = big.NewInt(1 << 1)
	internalAccountsInternalWebSetupRequestFieldPassword    = big.NewInt(1 << 2)
	internalAccountsInternalWebSetupRequestFieldPreferences = big.NewInt(1 << 3)
)

type InternalAccountsInternalWebSetupRequest struct {
	// Email is the admin email address, used as login credential and notification address.
	Email string `json:"email" url:"email"`
	// Name is an optional display name; defaults to the email prefix if empty.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Password is the admin password, >= 8 characters with at least one letter and one digit.
	Password    string                                                           `json:"password" url:"password"`
	Preferences *GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences `json:"preferences,omitempty" url:"preferences,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InternalAccountsInternalWebSetupRequest) GetEmail() string {
	if i == nil {
		return ""
	}
	return i.Email
}

func (i *InternalAccountsInternalWebSetupRequest) GetName() *string {
	if i == nil {
		return nil
	}
	return i.Name
}

func (i *InternalAccountsInternalWebSetupRequest) GetPassword() string {
	if i == nil {
		return ""
	}
	return i.Password
}

func (i *InternalAccountsInternalWebSetupRequest) GetPreferences() *GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences {
	if i == nil {
		return nil
	}
	return i.Preferences
}

func (i *InternalAccountsInternalWebSetupRequest) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InternalAccountsInternalWebSetupRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebSetupRequest) SetEmail(email string) {
	i.Email = email
	i.require(internalAccountsInternalWebSetupRequestFieldEmail)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebSetupRequest) SetName(name *string) {
	i.Name = name
	i.require(internalAccountsInternalWebSetupRequestFieldName)
}

// SetPassword sets the Password field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebSetupRequest) SetPassword(password string) {
	i.Password = password
	i.require(internalAccountsInternalWebSetupRequestFieldPassword)
}

// SetPreferences sets the Preferences field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebSetupRequest) SetPreferences(preferences *GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences) {
	i.Preferences = preferences
	i.require(internalAccountsInternalWebSetupRequestFieldPreferences)
}

func (i *InternalAccountsInternalWebSetupRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler InternalAccountsInternalWebSetupRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InternalAccountsInternalWebSetupRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InternalAccountsInternalWebSetupRequest) MarshalJSON() ([]byte, error) {
	type embed InternalAccountsInternalWebSetupRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InternalAccountsInternalWebSetupRequest) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	internalWisdomInternalWebWisdomDeleteVoFieldDeleted = big.NewInt(1 << 0)
)

type InternalWisdomInternalWebWisdomDeleteVo struct {
	Deleted *bool `json:"deleted,omitempty" url:"deleted,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InternalWisdomInternalWebWisdomDeleteVo) GetDeleted() *bool {
	if i == nil {
		return nil
	}
	return i.Deleted
}

func (i *InternalWisdomInternalWebWisdomDeleteVo) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InternalWisdomInternalWebWisdomDeleteVo) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetDeleted sets the Deleted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalWisdomInternalWebWisdomDeleteVo) SetDeleted(deleted *bool) {
	i.Deleted = deleted
	i.require(internalWisdomInternalWebWisdomDeleteVoFieldDeleted)
}

func (i *InternalWisdomInternalWebWisdomDeleteVo) UnmarshalJSON(data []byte) error {
	type unmarshaler InternalWisdomInternalWebWisdomDeleteVo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InternalWisdomInternalWebWisdomDeleteVo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InternalWisdomInternalWebWisdomDeleteVo) MarshalJSON() ([]byte, error) {
	type embed InternalWisdomInternalWebWisdomDeleteVo
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InternalWisdomInternalWebWisdomDeleteVo) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type PostSetupRequest struct {
	StringUnknownMap map[string]any
	// Admin credentials
	InternalAccountsInternalWebSetupRequest *InternalAccountsInternalWebSetupRequest

	typ string
}

func (p *PostSetupRequest) GetStringUnknownMap() map[string]any {
	if p == nil {
		return nil
	}
	return p.StringUnknownMap
}

func (p *PostSetupRequest) GetInternalAccountsInternalWebSetupRequest() *InternalAccountsInternalWebSetupRequest {
	if p == nil {
		return nil
	}
	return p.InternalAccountsInternalWebSetupRequest
}

func (p *PostSetupRequest) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMap map[string]any
	if err := json.Unmarshal(data, &valueStringUnknownMap); err == nil {
		p.typ = "StringUnknownMap"
		p.StringUnknownMap = valueStringUnknownMap
		return nil
	}
	valueInternalAccountsInternalWebSetupRequest := new(InternalAccountsInternalWebSetupRequest)
	if err := json.Unmarshal(data, &valueInternalAccountsInternalWebSetupRequest); err == nil {
		p.typ = "InternalAccountsInternalWebSetupRequest"
		p.InternalAccountsInternalWebSetupRequest = valueInternalAccountsInternalWebSetupRequest
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, p)
}

func (p PostSetupRequest) MarshalJSON() ([]byte, error) {
	if p.typ == "StringUnknownMap" || p.StringUnknownMap != nil {
		return json.Marshal(p.StringUnknownMap)
	}
	if p.typ == "InternalAccountsInternalWebSetupRequest" || p.InternalAccountsInternalWebSetupRequest != nil {
		return json.Marshal(p.InternalAccountsInternalWebSetupRequest)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", p)
}

type PostSetupRequestVisitor interface {
	VisitStringUnknownMap(map[string]any) error
	VisitInternalAccountsInternalWebSetupRequest(*InternalAccountsInternalWebSetupRequest) error
}

func (p *PostSetupRequest) Accept(visitor PostSetupRequestVisitor) error {
	if p.typ == "StringUnknownMap" || p.StringUnknownMap != nil {
		return visitor.VisitStringUnknownMap(p.StringUnknownMap)
	}
	if p.typ == "InternalAccountsInternalWebSetupRequest" || p.InternalAccountsInternalWebSetupRequest != nil {
		return visitor.VisitInternalAccountsInternalWebSetupRequest(p.InternalAccountsInternalWebSetupRequest)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", p)
}
