// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	big "math/big"
)

var (
	postGatewayUserIDRoutesIDFiltersRequestFieldUserID = big.NewInt(1 << 0)
	postGatewayUserIDRoutesIDFiltersRequestFieldID     = big.NewInt(1 << 1)
)

type PostGatewayUserIDRoutesIDFiltersRequest struct {
	// User ID
	UserID int `json:"-" url:"-"`
	// Route ID
	ID   int                                          `json:"-" url:"-"`
	Body *PostGatewayUserIDRoutesIDFiltersRequestBody `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostGatewayUserIDRoutesIDFiltersRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostGatewayUserIDRoutesIDFiltersRequest) SetUserID(userID int) {
	p.UserID = userID
	p.require(postGatewayUserIDRoutesIDFiltersRequestFieldUserID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostGatewayUserIDRoutesIDFiltersRequest) SetID(id int) {
	p.ID = id
	p.require(postGatewayUserIDRoutesIDFiltersRequestFieldID)
}

func (p *PostGatewayUserIDRoutesIDFiltersRequest) UnmarshalJSON(data []byte) error {
	body := new(PostGatewayUserIDRoutesIDFiltersRequestBody)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	p.Body = body
	return nil
}

func (p *PostGatewayUserIDRoutesIDFiltersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.Body)
}

var (
	postGatewayUserIDRoutesRequestFieldUserID = big.NewInt(1 << 0)
)

type PostGatewayUserIDRoutesRequest struct {
	// User ID
	UserID int                                 `json:"-" url:"-"`
	Body   *PostGatewayUserIDRoutesRequestBody `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostGatewayUserIDRoutesRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostGatewayUserIDRoutesRequest) SetUserID(userID int) {
	p.UserID = userID
	p.require(postGatewayUserIDRoutesRequestFieldUserID)
}

func (p *PostGatewayUserIDRoutesRequest) UnmarshalJSON(data []byte) error {
	body := new(PostGatewayUserIDRoutesRequestBody)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	p.Body = body
	return nil
}

func (p *PostGatewayUserIDRoutesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.Body)
}

var (
	deleteGatewayUserIDRoutesIDRequestFieldUserID = big.NewInt(1 << 0)
	deleteGatewayUserIDRoutesIDRequestFieldID     = big.NewInt(1 << 1)
)

type DeleteGatewayUserIDRoutesIDRequest struct {
	// User ID
	UserID int `json:"-" url:"-"`
	// Route ID
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteGatewayUserIDRoutesIDRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteGatewayUserIDRoutesIDRequest) SetUserID(userID int) {
	d.UserID = userID
	d.require(deleteGatewayUserIDRoutesIDRequestFieldUserID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteGatewayUserIDRoutesIDRequest) SetID(id int) {
	d.ID = id
	d.require(deleteGatewayUserIDRoutesIDRequestFieldID)
}

var (
	getGatewayUserIDRoutesIDRequestFieldUserID = big.NewInt(1 << 0)
	getGatewayUserIDRoutesIDRequestFieldID     = big.NewInt(1 << 1)
)

type GetGatewayUserIDRoutesIDRequest struct {
	// User ID
	UserID int `json:"-" url:"-"`
	// Route ID
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetGatewayUserIDRoutesIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetGatewayUserIDRoutesIDRequest) SetUserID(userID int) {
	g.UserID = userID
	g.require(getGatewayUserIDRoutesIDRequestFieldUserID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetGatewayUserIDRoutesIDRequest) SetID(id int) {
	g.ID = id
	g.require(getGatewayUserIDRoutesIDRequestFieldID)
}

var (
	getGatewayUserIDRoutesIDFiltersRequestFieldUserID = big.NewInt(1 << 0)
	getGatewayUserIDRoutesIDFiltersRequestFieldID     = big.NewInt(1 << 1)
)

type GetGatewayUserIDRoutesIDFiltersRequest struct {
	// User ID
	UserID int `json:"-" url:"-"`
	// Route ID
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetGatewayUserIDRoutesIDFiltersRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetGatewayUserIDRoutesIDFiltersRequest) SetUserID(userID int) {
	g.UserID = userID
	g.require(getGatewayUserIDRoutesIDFiltersRequestFieldUserID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetGatewayUserIDRoutesIDFiltersRequest) SetID(id int) {
	g.ID = id
	g.require(getGatewayUserIDRoutesIDFiltersRequestFieldID)
}

var (
	getGatewayUserIDRoutesRequestFieldUserID = big.NewInt(1 << 0)
)

type GetGatewayUserIDRoutesRequest struct {
	// User ID
	UserID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetGatewayUserIDRoutesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetGatewayUserIDRoutesRequest) SetUserID(userID int) {
	g.UserID = userID
	g.require(getGatewayUserIDRoutesRequestFieldUserID)
}

var (
	deleteGatewayUserIDRoutesIDFiltersTargetUserIDRequestFieldUserID       = big.NewInt(1 << 0)
	deleteGatewayUserIDRoutesIDFiltersTargetUserIDRequestFieldID           = big.NewInt(1 << 1)
	deleteGatewayUserIDRoutesIDFiltersTargetUserIDRequestFieldTargetUserID = big.NewInt(1 << 2)
)

type DeleteGatewayUserIDRoutesIDFiltersTargetUserIDRequest struct {
	// User ID
	UserID int `json:"-" url:"-"`
	// Route ID
	ID int `json:"-" url:"-"`
	// Target user ID
	TargetUserID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteGatewayUserIDRoutesIDFiltersTargetUserIDRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteGatewayUserIDRoutesIDFiltersTargetUserIDRequest) SetUserID(userID int) {
	d.UserID = userID
	d.require(deleteGatewayUserIDRoutesIDFiltersTargetUserIDRequestFieldUserID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteGatewayUserIDRoutesIDFiltersTargetUserIDRequest) SetID(id int) {
	d.ID = id
	d.require(deleteGatewayUserIDRoutesIDFiltersTargetUserIDRequestFieldID)
}

// SetTargetUserID sets the TargetUserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteGatewayUserIDRoutesIDFiltersTargetUserIDRequest) SetTargetUserID(targetUserID int) {
	d.TargetUserID = targetUserID
	d.require(deleteGatewayUserIDRoutesIDFiltersTargetUserIDRequestFieldTargetUserID)
}

var (
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldCode        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldData        = big.NewInt(1 << 1)
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldLimit       = big.NewInt(1 << 2)
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldMessage     = big.NewInt(1 << 3)
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldPage        = big.NewInt(1 << 4)
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldTotal       = big.NewInt(1 << 5)
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldUserMessage = big.NewInt(1 << 6)
)

type GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse struct {
	Code        *int                                             `json:"code,omitempty" url:"code,omitempty"`
	Data        []*InternalAigatewayInternalWebUserRouteResponse `json:"data,omitempty" url:"data,omitempty"`
	Limit       *int                                             `json:"limit,omitempty" url:"limit,omitempty"`
	Message     *string                                          `json:"message,omitempty" url:"message,omitempty"`
	Page        *int                                             `json:"page,omitempty" url:"page,omitempty"`
	Total       *int                                             `json:"total,omitempty" url:"total,omitempty"`
	UserMessage *string                                          `json:"user_message,omitempty" url:"user_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) GetData() []*InternalAigatewayInternalWebUserRouteResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) GetPage() *int {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) GetUserMessage() *string {
	if g == nil {
		return nil
	}
	return g.UserMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) SetCode(code *int) {
	g.Code = code
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldCode)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) SetData(data []*InternalAigatewayInternalWebUserRouteResponse) {
	g.Data = data
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) SetLimit(limit *int) {
	g.Limit = limit
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldLimit)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) SetMessage(message *string) {
	g.Message = message
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldMessage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) SetPage(page *int) {
	g.Page = page
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) SetTotal(total *int) {
	g.Total = total
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldTotal)
}

// SetUserMessage sets the UserMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) SetUserMessage(userMessage *string) {
	g.UserMessage = userMessage
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponseFieldUserMessage)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldCode        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldData        = big.NewInt(1 << 1)
	githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldLimit       = big.NewInt(1 << 2)
	githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldMessage     = big.NewInt(1 << 3)
	githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldPage        = big.NewInt(1 << 4)
	githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldTotal       = big.NewInt(1 << 5)
	githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldUserMessage = big.NewInt(1 << 6)
)

type GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse struct {
	Code        *int                                           `json:"code,omitempty" url:"code,omitempty"`
	Data        *InternalAigatewayInternalWebUserRouteResponse `json:"data,omitempty" url:"data,omitempty"`
	Limit       *int                                           `json:"limit,omitempty" url:"limit,omitempty"`
	Message     *string                                        `json:"message,omitempty" url:"message,omitempty"`
	Page        *int                                           `json:"page,omitempty" url:"page,omitempty"`
	Total       *int                                           `json:"total,omitempty" url:"total,omitempty"`
	UserMessage *string                                        `json:"user_message,omitempty" url:"user_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) GetData() *InternalAigatewayInternalWebUserRouteResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) GetPage() *int {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) GetUserMessage() *string {
	if g == nil {
		return nil
	}
	return g.UserMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) SetCode(code *int) {
	g.Code = code
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldCode)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) SetData(data *InternalAigatewayInternalWebUserRouteResponse) {
	g.Data = data
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) SetLimit(limit *int) {
	g.Limit = limit
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldLimit)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) SetMessage(message *string) {
	g.Message = message
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldMessage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) SetPage(page *int) {
	g.Page = page
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) SetTotal(total *int) {
	g.Total = total
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldTotal)
}

// SetUserMessage sets the UserMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) SetUserMessage(userMessage *string) {
	g.UserMessage = userMessage
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponseFieldUserMessage)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	internalAigatewayInternalWebAddRouteFilterRequestFieldUserID = big.NewInt(1 << 0)
)

type InternalAigatewayInternalWebAddRouteFilterRequest struct {
	// UserID is the target user ID to grant route access.
	UserID *int `json:"user_id,omitempty" url:"user_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InternalAigatewayInternalWebAddRouteFilterRequest) GetUserID() *int {
	if i == nil {
		return nil
	}
	return i.UserID
}

func (i *InternalAigatewayInternalWebAddRouteFilterRequest) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InternalAigatewayInternalWebAddRouteFilterRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAigatewayInternalWebAddRouteFilterRequest) SetUserID(userID *int) {
	i.UserID = userID
	i.require(internalAigatewayInternalWebAddRouteFilterRequestFieldUserID)
}

func (i *InternalAigatewayInternalWebAddRouteFilterRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler InternalAigatewayInternalWebAddRouteFilterRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InternalAigatewayInternalWebAddRouteFilterRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InternalAigatewayInternalWebAddRouteFilterRequest) MarshalJSON() ([]byte, error) {
	type embed InternalAigatewayInternalWebAddRouteFilterRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InternalAigatewayInternalWebAddRouteFilterRequest) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	internalAigatewayInternalWebUserRouteRequestFieldAlgorithm  = big.NewInt(1 << 0)
	internalAigatewayInternalWebUserRouteRequestFieldName       = big.NewInt(1 << 1)
	internalAigatewayInternalWebUserRouteRequestFieldTargets    = big.NewInt(1 << 2)
	internalAigatewayInternalWebUserRouteRequestFieldVisibility = big.NewInt(1 << 3)
)

type InternalAigatewayInternalWebUserRouteRequest struct {
	// Algorithm is the routing algorithm (currently only targets[0] is used).
	Algorithm *string `json:"algorithm,omitempty" url:"algorithm,omitempty"`
	// Name is the route name (unique per user).
	Name string `json:"name" url:"name"`
	// Targets is the ordered list of model IDs for this route.
	Targets []int `json:"targets" url:"targets"`
	// Visibility is the route visibility (private or public).
	Visibility *string `json:"visibility,omitempty" url:"visibility,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InternalAigatewayInternalWebUserRouteRequest) GetAlgorithm() *string {
	if i == nil {
		return nil
	}
	return i.Algorithm
}

func (i *InternalAigatewayInternalWebUserRouteRequest) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *InternalAigatewayInternalWebUserRouteRequest) GetTargets() []int {
	if i == nil {
		return nil
	}
	return i.Targets
}

func (i *InternalAigatewayInternalWebUserRouteRequest) GetVisibility() *string {
	if i == nil {
		return nil
	}
	return i.Visibility
}

func (i *InternalAigatewayInternalWebUserRouteRequest) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InternalAigatewayInternalWebUserRouteRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetAlgorithm sets the Algorithm field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAigatewayInternalWebUserRouteRequest) SetAlgorithm(algorithm *string) {
	i.Algorithm = algorithm
	i.require(internalAigatewayInternalWebUserRouteRequestFieldAlgorithm)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAigatewayInternalWebUserRouteRequest) SetName(name string) {
	i.Name = name
	i.require(internalAigatewayInternalWebUserRouteRequestFieldName)
}

// SetTargets sets the Targets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAigatewayInternalWebUserRouteRequest) SetTargets(targets []int) {
	i.Targets = targets
	i.require(internalAigatewayInternalWebUserRouteRequestFieldTargets)
}

// SetVisibility sets the Visibility field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAigatewayInternalWebUserRouteRequest) SetVisibility(visibility *string) {
	i.Visibility = visibility
	i.require(internalAigatewayInternalWebUserRouteRequestFieldVisibility)
}

func (i *InternalAigatewayInternalWebUserRouteRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler InternalAigatewayInternalWebUserRouteRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InternalAigatewayInternalWebUserRouteRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InternalAigatewayInternalWebUserRouteRequest) MarshalJSON() ([]byte, error) {
	type embed InternalAigatewayInternalWebUserRouteRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InternalAigatewayInternalWebUserRouteRequest) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// User route with target model list.
var (
	internalAigatewayInternalWebUserRouteResponseFieldAlgorithm   = big.NewInt(1 << 0)
	internalAigatewayInternalWebUserRouteResponseFieldDescription = big.NewInt(1 << 1)
	internalAigatewayInternalWebUserRouteResponseFieldID          = big.NewInt(1 << 2)
	internalAigatewayInternalWebUserRouteResponseFieldName        = big.NewInt(1 << 3)
	internalAigatewayInternalWebUserRouteResponseFieldTargets     = big.NewInt(1 << 4)
	internalAigatewayInternalWebUserRouteResponseFieldUserID      = big.NewInt(1 << 5)
	internalAigatewayInternalWebUserRouteResponseFieldVisibility  = big.NewInt(1 << 6)
)

type InternalAigatewayInternalWebUserRouteResponse struct {
	// Algorithm is the routing algorithm.
	Algorithm *string `json:"algorithm,omitempty" url:"algorithm,omitempty"`
	// Description is an optional description.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// ID is the route ID.
	ID *int `json:"id,omitempty" url:"id,omitempty"`
	// Name is the route name.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Targets is the ordered list of target model IDs.
	Targets []int `json:"targets,omitempty" url:"targets,omitempty"`
	// UserID is the owner user ID.
	UserID *int `json:"user_id,omitempty" url:"user_id,omitempty"`
	// Visibility is the route visibility.
	Visibility *string `json:"visibility,omitempty" url:"visibility,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InternalAigatewayInternalWebUserRouteResponse) GetAlgorithm() *string {
	if i == nil {
		return nil
	}
	return i.Algorithm
}

func (i *InternalAigatewayInternalWebUserRouteResponse) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *InternalAigatewayInternalWebUserRouteResponse) GetID() *int {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *InternalAigatewayInternalWebUserRouteResponse) GetName() *string {
	if i == nil {
		return nil
	}
	return i.Name
}

func (i *InternalAigatewayInternalWebUserRouteResponse) GetTargets() []int {
	if i == nil {
		return nil
	}
	return i.Targets
}

func (i *InternalAigatewayInternalWebUserRouteResponse) GetUserID() *int {
	if i == nil {
		return nil
	}
	return i.UserID
}

func (i *InternalAigatewayInternalWebUserRouteResponse) GetVisibility() *string {
	if i == nil {
		return nil
	}
	return i.Visibility
}

func (i *InternalAigatewayInternalWebUserRouteResponse) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InternalAigatewayInternalWebUserRouteResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetAlgorithm sets the Algorithm field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAigatewayInternalWebUserRouteResponse) SetAlgorithm(algorithm *string) {
	i.Algorithm = algorithm
	i.require(internalAigatewayInternalWebUserRouteResponseFieldAlgorithm)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAigatewayInternalWebUserRouteResponse) SetDescription(description *string) {
	i.Description = description
	i.require(internalAigatewayInternalWebUserRouteResponseFieldDescription)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAigatewayInternalWebUserRouteResponse) SetID(id *int) {
	i.ID = id
	i.require(internalAigatewayInternalWebUserRouteResponseFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAigatewayInternalWebUserRouteResponse) SetName(name *string) {
	i.Name = name
	i.require(internalAigatewayInternalWebUserRouteResponseFieldName)
}

// SetTargets sets the Targets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAigatewayInternalWebUserRouteResponse) SetTargets(targets []int) {
	i.Targets = targets
	i.require(internalAigatewayInternalWebUserRouteResponseFieldTargets)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAigatewayInternalWebUserRouteResponse) SetUserID(userID *int) {
	i.UserID = userID
	i.require(internalAigatewayInternalWebUserRouteResponseFieldUserID)
}

// SetVisibility sets the Visibility field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAigatewayInternalWebUserRouteResponse) SetVisibility(visibility *string) {
	i.Visibility = visibility
	i.require(internalAigatewayInternalWebUserRouteResponseFieldVisibility)
}

func (i *InternalAigatewayInternalWebUserRouteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler InternalAigatewayInternalWebUserRouteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InternalAigatewayInternalWebUserRouteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InternalAigatewayInternalWebUserRouteResponse) MarshalJSON() ([]byte, error) {
	type embed InternalAigatewayInternalWebUserRouteResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InternalAigatewayInternalWebUserRouteResponse) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type PostGatewayUserIDRoutesIDFiltersRequestBody struct {
	StringUnknownMap map[string]any
	// Target user ID
	InternalAigatewayInternalWebAddRouteFilterRequest *InternalAigatewayInternalWebAddRouteFilterRequest

	typ string
}

func (p *PostGatewayUserIDRoutesIDFiltersRequestBody) GetStringUnknownMap() map[string]any {
	if p == nil {
		return nil
	}
	return p.StringUnknownMap
}

func (p *PostGatewayUserIDRoutesIDFiltersRequestBody) GetInternalAigatewayInternalWebAddRouteFilterRequest() *InternalAigatewayInternalWebAddRouteFilterRequest {
	if p == nil {
		return nil
	}
	return p.InternalAigatewayInternalWebAddRouteFilterRequest
}

func (p *PostGatewayUserIDRoutesIDFiltersRequestBody) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMap map[string]any
	if err := json.Unmarshal(data, &valueStringUnknownMap); err == nil {
		p.typ = "StringUnknownMap"
		p.StringUnknownMap = valueStringUnknownMap
		return nil
	}
	valueInternalAigatewayInternalWebAddRouteFilterRequest := new(InternalAigatewayInternalWebAddRouteFilterRequest)
	if err := json.Unmarshal(data, &valueInternalAigatewayInternalWebAddRouteFilterRequest); err == nil {
		p.typ = "InternalAigatewayInternalWebAddRouteFilterRequest"
		p.InternalAigatewayInternalWebAddRouteFilterRequest = valueInternalAigatewayInternalWebAddRouteFilterRequest
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, p)
}

func (p PostGatewayUserIDRoutesIDFiltersRequestBody) MarshalJSON() ([]byte, error) {
	if p.typ == "StringUnknownMap" || p.StringUnknownMap != nil {
		return json.Marshal(p.StringUnknownMap)
	}
	if p.typ == "InternalAigatewayInternalWebAddRouteFilterRequest" || p.InternalAigatewayInternalWebAddRouteFilterRequest != nil {
		return json.Marshal(p.InternalAigatewayInternalWebAddRouteFilterRequest)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", p)
}

type PostGatewayUserIDRoutesIDFiltersRequestBodyVisitor interface {
	VisitStringUnknownMap(map[string]any) error
	VisitInternalAigatewayInternalWebAddRouteFilterRequest(*InternalAigatewayInternalWebAddRouteFilterRequest) error
}

func (p *PostGatewayUserIDRoutesIDFiltersRequestBody) Accept(visitor PostGatewayUserIDRoutesIDFiltersRequestBodyVisitor) error {
	if p.typ == "StringUnknownMap" || p.StringUnknownMap != nil {
		return visitor.VisitStringUnknownMap(p.StringUnknownMap)
	}
	if p.typ == "InternalAigatewayInternalWebAddRouteFilterRequest" || p.InternalAigatewayInternalWebAddRouteFilterRequest != nil {
		return visitor.VisitInternalAigatewayInternalWebAddRouteFilterRequest(p.InternalAigatewayInternalWebAddRouteFilterRequest)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", p)
}

type PostGatewayUserIDRoutesRequestBody struct {
	StringUnknownMap map[string]any
	// Route details
	InternalAigatewayInternalWebUserRouteRequest *InternalAigatewayInternalWebUserRouteRequest

	typ string
}

func (p *PostGatewayUserIDRoutesRequestBody) GetStringUnknownMap() map[string]any {
	if p == nil {
		return nil
	}
	return p.StringUnknownMap
}

func (p *PostGatewayUserIDRoutesRequestBody) GetInternalAigatewayInternalWebUserRouteRequest() *InternalAigatewayInternalWebUserRouteRequest {
	if p == nil {
		return nil
	}
	return p.InternalAigatewayInternalWebUserRouteRequest
}

func (p *PostGatewayUserIDRoutesRequestBody) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMap map[string]any
	if err := json.Unmarshal(data, &valueStringUnknownMap); err == nil {
		p.typ = "StringUnknownMap"
		p.StringUnknownMap = valueStringUnknownMap
		return nil
	}
	valueInternalAigatewayInternalWebUserRouteRequest := new(InternalAigatewayInternalWebUserRouteRequest)
	if err := json.Unmarshal(data, &valueInternalAigatewayInternalWebUserRouteRequest); err == nil {
		p.typ = "InternalAigatewayInternalWebUserRouteRequest"
		p.InternalAigatewayInternalWebUserRouteRequest = valueInternalAigatewayInternalWebUserRouteRequest
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, p)
}

func (p PostGatewayUserIDRoutesRequestBody) MarshalJSON() ([]byte, error) {
	if p.typ == "StringUnknownMap" || p.StringUnknownMap != nil {
		return json.Marshal(p.StringUnknownMap)
	}
	if p.typ == "InternalAigatewayInternalWebUserRouteRequest" || p.InternalAigatewayInternalWebUserRouteRequest != nil {
		return json.Marshal(p.InternalAigatewayInternalWebUserRouteRequest)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", p)
}

type PostGatewayUserIDRoutesRequestBodyVisitor interface {
	VisitStringUnknownMap(map[string]any) error
	VisitInternalAigatewayInternalWebUserRouteRequest(*InternalAigatewayInternalWebUserRouteRequest) error
}

func (p *PostGatewayUserIDRoutesRequestBody) Accept(visitor PostGatewayUserIDRoutesRequestBodyVisitor) error {
	if p.typ == "StringUnknownMap" || p.StringUnknownMap != nil {
		return visitor.VisitStringUnknownMap(p.StringUnknownMap)
	}
	if p.typ == "InternalAigatewayInternalWebUserRouteRequest" || p.InternalAigatewayInternalWebUserRouteRequest != nil {
		return visitor.VisitInternalAigatewayInternalWebUserRouteRequest(p.InternalAigatewayInternalWebUserRouteRequest)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", p)
}
