// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	big "math/big"
)

var (
	postGatewayUserIDModelsIDFiltersRequestFieldUserID = big.NewInt(1 << 0)
	postGatewayUserIDModelsIDFiltersRequestFieldID     = big.NewInt(1 << 1)
)

type PostGatewayUserIDModelsIDFiltersRequest struct {
	// User ID
	UserID int `json:"-" url:"-"`
	// Model ID
	ID   int                                          `json:"-" url:"-"`
	Body *PostGatewayUserIDModelsIDFiltersRequestBody `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostGatewayUserIDModelsIDFiltersRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostGatewayUserIDModelsIDFiltersRequest) SetUserID(userID int) {
	p.UserID = userID
	p.require(postGatewayUserIDModelsIDFiltersRequestFieldUserID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostGatewayUserIDModelsIDFiltersRequest) SetID(id int) {
	p.ID = id
	p.require(postGatewayUserIDModelsIDFiltersRequestFieldID)
}

func (p *PostGatewayUserIDModelsIDFiltersRequest) UnmarshalJSON(data []byte) error {
	body := new(PostGatewayUserIDModelsIDFiltersRequestBody)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	p.Body = body
	return nil
}

func (p *PostGatewayUserIDModelsIDFiltersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.Body)
}

var (
	getGatewayUserIDModelsIDFiltersRequestFieldUserID = big.NewInt(1 << 0)
	getGatewayUserIDModelsIDFiltersRequestFieldID     = big.NewInt(1 << 1)
)

type GetGatewayUserIDModelsIDFiltersRequest struct {
	// User ID
	UserID int `json:"-" url:"-"`
	// Model ID
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetGatewayUserIDModelsIDFiltersRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetGatewayUserIDModelsIDFiltersRequest) SetUserID(userID int) {
	g.UserID = userID
	g.require(getGatewayUserIDModelsIDFiltersRequestFieldUserID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetGatewayUserIDModelsIDFiltersRequest) SetID(id int) {
	g.ID = id
	g.require(getGatewayUserIDModelsIDFiltersRequestFieldID)
}

var (
	deleteGatewayUserIDModelsIDFiltersTargetUserIDRequestFieldUserID       = big.NewInt(1 << 0)
	deleteGatewayUserIDModelsIDFiltersTargetUserIDRequestFieldID           = big.NewInt(1 << 1)
	deleteGatewayUserIDModelsIDFiltersTargetUserIDRequestFieldTargetUserID = big.NewInt(1 << 2)
)

type DeleteGatewayUserIDModelsIDFiltersTargetUserIDRequest struct {
	// User ID
	UserID int `json:"-" url:"-"`
	// Model ID
	ID int `json:"-" url:"-"`
	// Target user ID
	TargetUserID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteGatewayUserIDModelsIDFiltersTargetUserIDRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteGatewayUserIDModelsIDFiltersTargetUserIDRequest) SetUserID(userID int) {
	d.UserID = userID
	d.require(deleteGatewayUserIDModelsIDFiltersTargetUserIDRequestFieldUserID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteGatewayUserIDModelsIDFiltersTargetUserIDRequest) SetID(id int) {
	d.ID = id
	d.require(deleteGatewayUserIDModelsIDFiltersTargetUserIDRequestFieldID)
}

// SetTargetUserID sets the TargetUserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteGatewayUserIDModelsIDFiltersTargetUserIDRequest) SetTargetUserID(targetUserID int) {
	d.TargetUserID = targetUserID
	d.require(deleteGatewayUserIDModelsIDFiltersTargetUserIDRequestFieldTargetUserID)
}

var (
	internalAigatewayInternalWebAddModelFilterRequestFieldUserID = big.NewInt(1 << 0)
)

type InternalAigatewayInternalWebAddModelFilterRequest struct {
	// UserID is the target user ID to grant model access.
	UserID *int `json:"user_id,omitempty" url:"user_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InternalAigatewayInternalWebAddModelFilterRequest) GetUserID() *int {
	if i == nil {
		return nil
	}
	return i.UserID
}

func (i *InternalAigatewayInternalWebAddModelFilterRequest) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InternalAigatewayInternalWebAddModelFilterRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAigatewayInternalWebAddModelFilterRequest) SetUserID(userID *int) {
	i.UserID = userID
	i.require(internalAigatewayInternalWebAddModelFilterRequestFieldUserID)
}

func (i *InternalAigatewayInternalWebAddModelFilterRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler InternalAigatewayInternalWebAddModelFilterRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InternalAigatewayInternalWebAddModelFilterRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InternalAigatewayInternalWebAddModelFilterRequest) MarshalJSON() ([]byte, error) {
	type embed InternalAigatewayInternalWebAddModelFilterRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InternalAigatewayInternalWebAddModelFilterRequest) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type PostGatewayUserIDModelsIDFiltersRequestBody struct {
	StringUnknownMap map[string]any
	// Target user ID
	InternalAigatewayInternalWebAddModelFilterRequest *InternalAigatewayInternalWebAddModelFilterRequest

	typ string
}

func (p *PostGatewayUserIDModelsIDFiltersRequestBody) GetStringUnknownMap() map[string]any {
	if p == nil {
		return nil
	}
	return p.StringUnknownMap
}

func (p *PostGatewayUserIDModelsIDFiltersRequestBody) GetInternalAigatewayInternalWebAddModelFilterRequest() *InternalAigatewayInternalWebAddModelFilterRequest {
	if p == nil {
		return nil
	}
	return p.InternalAigatewayInternalWebAddModelFilterRequest
}

func (p *PostGatewayUserIDModelsIDFiltersRequestBody) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMap map[string]any
	if err := json.Unmarshal(data, &valueStringUnknownMap); err == nil {
		p.typ = "StringUnknownMap"
		p.StringUnknownMap = valueStringUnknownMap
		return nil
	}
	valueInternalAigatewayInternalWebAddModelFilterRequest := new(InternalAigatewayInternalWebAddModelFilterRequest)
	if err := json.Unmarshal(data, &valueInternalAigatewayInternalWebAddModelFilterRequest); err == nil {
		p.typ = "InternalAigatewayInternalWebAddModelFilterRequest"
		p.InternalAigatewayInternalWebAddModelFilterRequest = valueInternalAigatewayInternalWebAddModelFilterRequest
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, p)
}

func (p PostGatewayUserIDModelsIDFiltersRequestBody) MarshalJSON() ([]byte, error) {
	if p.typ == "StringUnknownMap" || p.StringUnknownMap != nil {
		return json.Marshal(p.StringUnknownMap)
	}
	if p.typ == "InternalAigatewayInternalWebAddModelFilterRequest" || p.InternalAigatewayInternalWebAddModelFilterRequest != nil {
		return json.Marshal(p.InternalAigatewayInternalWebAddModelFilterRequest)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", p)
}

type PostGatewayUserIDModelsIDFiltersRequestBodyVisitor interface {
	VisitStringUnknownMap(map[string]any) error
	VisitInternalAigatewayInternalWebAddModelFilterRequest(*InternalAigatewayInternalWebAddModelFilterRequest) error
}

func (p *PostGatewayUserIDModelsIDFiltersRequestBody) Accept(visitor PostGatewayUserIDModelsIDFiltersRequestBodyVisitor) error {
	if p.typ == "StringUnknownMap" || p.StringUnknownMap != nil {
		return visitor.VisitStringUnknownMap(p.StringUnknownMap)
	}
	if p.typ == "InternalAigatewayInternalWebAddModelFilterRequest" || p.InternalAigatewayInternalWebAddModelFilterRequest != nil {
		return visitor.VisitInternalAigatewayInternalWebAddModelFilterRequest(p.InternalAigatewayInternalWebAddModelFilterRequest)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", p)
}
