// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	big "math/big"
)

var (
	putSecretsUserIDKeyRequestFieldUserID = big.NewInt(1 << 0)
	putSecretsUserIDKeyRequestFieldKey    = big.NewInt(1 << 1)
)

type PutSecretsUserIDKeyRequest struct {
	// User ID
	UserID int `json:"-" url:"-"`
	// Secret key
	Key  string                          `json:"-" url:"-"`
	Body *PutSecretsUserIDKeyRequestBody `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PutSecretsUserIDKeyRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PutSecretsUserIDKeyRequest) SetUserID(userID int) {
	p.UserID = userID
	p.require(putSecretsUserIDKeyRequestFieldUserID)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PutSecretsUserIDKeyRequest) SetKey(key string) {
	p.Key = key
	p.require(putSecretsUserIDKeyRequestFieldKey)
}

func (p *PutSecretsUserIDKeyRequest) UnmarshalJSON(data []byte) error {
	body := new(PutSecretsUserIDKeyRequestBody)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	p.Body = body
	return nil
}

func (p *PutSecretsUserIDKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.Body)
}

var (
	deleteSecretsUserIDKeyRequestFieldUserID = big.NewInt(1 << 0)
	deleteSecretsUserIDKeyRequestFieldKey    = big.NewInt(1 << 1)
)

type DeleteSecretsUserIDKeyRequest struct {
	// User ID
	UserID int `json:"-" url:"-"`
	// Secret key
	Key string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteSecretsUserIDKeyRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSecretsUserIDKeyRequest) SetUserID(userID int) {
	d.UserID = userID
	d.require(deleteSecretsUserIDKeyRequestFieldUserID)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSecretsUserIDKeyRequest) SetKey(key string) {
	d.Key = key
	d.require(deleteSecretsUserIDKeyRequestFieldKey)
}

var (
	getSecretsUserIDKeyRequestFieldUserID = big.NewInt(1 << 0)
	getSecretsUserIDKeyRequestFieldKey    = big.NewInt(1 << 1)
)

type GetSecretsUserIDKeyRequest struct {
	// User ID
	UserID int `json:"-" url:"-"`
	// Secret key
	Key string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetSecretsUserIDKeyRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSecretsUserIDKeyRequest) SetUserID(userID int) {
	g.UserID = userID
	g.require(getSecretsUserIDKeyRequestFieldUserID)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSecretsUserIDKeyRequest) SetKey(key string) {
	g.Key = key
	g.require(getSecretsUserIDKeyRequestFieldKey)
}

var (
	getSecretsUserIDRequestFieldUserID = big.NewInt(1 << 0)
)

type GetSecretsUserIDRequest struct {
	// User ID
	UserID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetSecretsUserIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSecretsUserIDRequest) SetUserID(userID int) {
	g.UserID = userID
	g.require(getSecretsUserIDRequestFieldUserID)
}

var (
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldCode        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldData        = big.NewInt(1 << 1)
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldLimit       = big.NewInt(1 << 2)
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldMessage     = big.NewInt(1 << 3)
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldPage        = big.NewInt(1 << 4)
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldTotal       = big.NewInt(1 << 5)
	githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldUserMessage = big.NewInt(1 << 6)
)

type GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse struct {
	Code        *int                                             `json:"code,omitempty" url:"code,omitempty"`
	Data        []*InternalAccountsInternalWebUserSecretResponse `json:"data,omitempty" url:"data,omitempty"`
	Limit       *int                                             `json:"limit,omitempty" url:"limit,omitempty"`
	Message     *string                                          `json:"message,omitempty" url:"message,omitempty"`
	Page        *int                                             `json:"page,omitempty" url:"page,omitempty"`
	Total       *int                                             `json:"total,omitempty" url:"total,omitempty"`
	UserMessage *string                                          `json:"user_message,omitempty" url:"user_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) GetData() []*InternalAccountsInternalWebUserSecretResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) GetPage() *int {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) GetUserMessage() *string {
	if g == nil {
		return nil
	}
	return g.UserMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) SetCode(code *int) {
	g.Code = code
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldCode)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) SetData(data []*InternalAccountsInternalWebUserSecretResponse) {
	g.Data = data
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) SetLimit(limit *int) {
	g.Limit = limit
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldLimit)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) SetMessage(message *string) {
	g.Message = message
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldMessage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) SetPage(page *int) {
	g.Page = page
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) SetTotal(total *int) {
	g.Total = total
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldTotal)
}

// SetUserMessage sets the UserMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) SetUserMessage(userMessage *string) {
	g.UserMessage = userMessage
	g.require(githubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponseFieldUserMessage)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultArrayInternalAccountsInternalWebUserSecretResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldCode        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldData        = big.NewInt(1 << 1)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldLimit       = big.NewInt(1 << 2)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldMessage     = big.NewInt(1 << 3)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldPage        = big.NewInt(1 << 4)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldTotal       = big.NewInt(1 << 5)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldUserMessage = big.NewInt(1 << 6)
)

type GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse struct {
	Code        *int                                                 `json:"code,omitempty" url:"code,omitempty"`
	Data        *InternalAccountsInternalWebDeleteUserSecretResponse `json:"data,omitempty" url:"data,omitempty"`
	Limit       *int                                                 `json:"limit,omitempty" url:"limit,omitempty"`
	Message     *string                                              `json:"message,omitempty" url:"message,omitempty"`
	Page        *int                                                 `json:"page,omitempty" url:"page,omitempty"`
	Total       *int                                                 `json:"total,omitempty" url:"total,omitempty"`
	UserMessage *string                                              `json:"user_message,omitempty" url:"user_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) GetData() *InternalAccountsInternalWebDeleteUserSecretResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) GetPage() *int {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) GetUserMessage() *string {
	if g == nil {
		return nil
	}
	return g.UserMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) SetCode(code *int) {
	g.Code = code
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldCode)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) SetData(data *InternalAccountsInternalWebDeleteUserSecretResponse) {
	g.Data = data
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) SetLimit(limit *int) {
	g.Limit = limit
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldLimit)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) SetMessage(message *string) {
	g.Message = message
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldMessage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) SetPage(page *int) {
	g.Page = page
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) SetTotal(total *int) {
	g.Total = total
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldTotal)
}

// SetUserMessage sets the UserMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) SetUserMessage(userMessage *string) {
	g.UserMessage = userMessage
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponseFieldUserMessage)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebDeleteUserSecretResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldCode        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldData        = big.NewInt(1 << 1)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldLimit       = big.NewInt(1 << 2)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldMessage     = big.NewInt(1 << 3)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldPage        = big.NewInt(1 << 4)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldTotal       = big.NewInt(1 << 5)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldUserMessage = big.NewInt(1 << 6)
)

type GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse struct {
	Code        *int                                           `json:"code,omitempty" url:"code,omitempty"`
	Data        *InternalAccountsInternalWebUserSecretResponse `json:"data,omitempty" url:"data,omitempty"`
	Limit       *int                                           `json:"limit,omitempty" url:"limit,omitempty"`
	Message     *string                                        `json:"message,omitempty" url:"message,omitempty"`
	Page        *int                                           `json:"page,omitempty" url:"page,omitempty"`
	Total       *int                                           `json:"total,omitempty" url:"total,omitempty"`
	UserMessage *string                                        `json:"user_message,omitempty" url:"user_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) GetData() *InternalAccountsInternalWebUserSecretResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) GetPage() *int {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) GetUserMessage() *string {
	if g == nil {
		return nil
	}
	return g.UserMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) SetCode(code *int) {
	g.Code = code
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldCode)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) SetData(data *InternalAccountsInternalWebUserSecretResponse) {
	g.Data = data
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) SetLimit(limit *int) {
	g.Limit = limit
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldLimit)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) SetMessage(message *string) {
	g.Message = message
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldMessage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) SetPage(page *int) {
	g.Page = page
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) SetTotal(total *int) {
	g.Total = total
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldTotal)
}

// SetUserMessage sets the UserMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) SetUserMessage(userMessage *string) {
	g.UserMessage = userMessage
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponseFieldUserMessage)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldCode        = big.NewInt(1 << 0)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldData        = big.NewInt(1 << 1)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldLimit       = big.NewInt(1 << 2)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldMessage     = big.NewInt(1 << 3)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldPage        = big.NewInt(1 << 4)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldTotal       = big.NewInt(1 << 5)
	githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldUserMessage = big.NewInt(1 << 6)
)

type GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse struct {
	Code        *int                                                `json:"code,omitempty" url:"code,omitempty"`
	Data        *InternalAccountsInternalWebUserSecretValueResponse `json:"data,omitempty" url:"data,omitempty"`
	Limit       *int                                                `json:"limit,omitempty" url:"limit,omitempty"`
	Message     *string                                             `json:"message,omitempty" url:"message,omitempty"`
	Page        *int                                                `json:"page,omitempty" url:"page,omitempty"`
	Total       *int                                                `json:"total,omitempty" url:"total,omitempty"`
	UserMessage *string                                             `json:"user_message,omitempty" url:"user_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) GetData() *InternalAccountsInternalWebUserSecretValueResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) GetPage() *int {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) GetUserMessage() *string {
	if g == nil {
		return nil
	}
	return g.UserMessage
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) SetCode(code *int) {
	g.Code = code
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldCode)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) SetData(data *InternalAccountsInternalWebUserSecretValueResponse) {
	g.Data = data
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) SetLimit(limit *int) {
	g.Limit = limit
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldLimit)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) SetMessage(message *string) {
	g.Message = message
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldMessage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) SetPage(page *int) {
	g.Page = page
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldPage)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) SetTotal(total *int) {
	g.Total = total
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldTotal)
}

// SetUserMessage sets the UserMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) SetUserMessage(userMessage *string) {
	g.UserMessage = userMessage
	g.require(githubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponseFieldUserMessage)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) MarshalJSON() ([]byte, error) {
	type embed GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebUserSecretValueResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Deletion confirmation.
var (
	internalAccountsInternalWebDeleteUserSecretResponseFieldDeleted = big.NewInt(1 << 0)
)

type InternalAccountsInternalWebDeleteUserSecretResponse struct {
	// Deleted indicates whether the secret was successfully deleted.
	Deleted *bool `json:"deleted,omitempty" url:"deleted,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InternalAccountsInternalWebDeleteUserSecretResponse) GetDeleted() *bool {
	if i == nil {
		return nil
	}
	return i.Deleted
}

func (i *InternalAccountsInternalWebDeleteUserSecretResponse) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InternalAccountsInternalWebDeleteUserSecretResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetDeleted sets the Deleted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebDeleteUserSecretResponse) SetDeleted(deleted *bool) {
	i.Deleted = deleted
	i.require(internalAccountsInternalWebDeleteUserSecretResponseFieldDeleted)
}

func (i *InternalAccountsInternalWebDeleteUserSecretResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler InternalAccountsInternalWebDeleteUserSecretResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InternalAccountsInternalWebDeleteUserSecretResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InternalAccountsInternalWebDeleteUserSecretResponse) MarshalJSON() ([]byte, error) {
	type embed InternalAccountsInternalWebDeleteUserSecretResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InternalAccountsInternalWebDeleteUserSecretResponse) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Secret value and description for create/update.
var (
	internalAccountsInternalWebUpsertSecretReqFieldDescription = big.NewInt(1 << 0)
	internalAccountsInternalWebUpsertSecretReqFieldValue       = big.NewInt(1 << 1)
)

type InternalAccountsInternalWebUpsertSecretReq struct {
	// Description is an optional human-readable description of the secret (max 8KiB).
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Value is the secret value to encrypt and store (max 64KiB).
	Value *string `json:"value,omitempty" url:"value,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InternalAccountsInternalWebUpsertSecretReq) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *InternalAccountsInternalWebUpsertSecretReq) GetValue() *string {
	if i == nil {
		return nil
	}
	return i.Value
}

func (i *InternalAccountsInternalWebUpsertSecretReq) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InternalAccountsInternalWebUpsertSecretReq) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebUpsertSecretReq) SetDescription(description *string) {
	i.Description = description
	i.require(internalAccountsInternalWebUpsertSecretReqFieldDescription)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebUpsertSecretReq) SetValue(value *string) {
	i.Value = value
	i.require(internalAccountsInternalWebUpsertSecretReqFieldValue)
}

func (i *InternalAccountsInternalWebUpsertSecretReq) UnmarshalJSON(data []byte) error {
	type unmarshaler InternalAccountsInternalWebUpsertSecretReq
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InternalAccountsInternalWebUpsertSecretReq(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InternalAccountsInternalWebUpsertSecretReq) MarshalJSON() ([]byte, error) {
	type embed InternalAccountsInternalWebUpsertSecretReq
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InternalAccountsInternalWebUpsertSecretReq) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// User secret metadata without the decrypted value.
var (
	internalAccountsInternalWebUserSecretResponseFieldCreatedAt   = big.NewInt(1 << 0)
	internalAccountsInternalWebUserSecretResponseFieldDescription = big.NewInt(1 << 1)
	internalAccountsInternalWebUserSecretResponseFieldKey         = big.NewInt(1 << 2)
	internalAccountsInternalWebUserSecretResponseFieldUpdatedAt   = big.NewInt(1 << 3)
	internalAccountsInternalWebUserSecretResponseFieldUserID      = big.NewInt(1 << 4)
)

type InternalAccountsInternalWebUserSecretResponse struct {
	// CreatedAt is the Unix timestamp of when the secret was created.
	CreatedAt *int `json:"created_at,omitempty" url:"created_at,omitempty"`
	// Description is a human-readable description of the secret.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Key is the unique key identifying this secret within the user's namespace.
	Key *string `json:"key,omitempty" url:"key,omitempty"`
	// UpdatedAt is the Unix timestamp of when the secret was last updated.
	UpdatedAt *int `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	// UserID is the ID of the user who owns this secret.
	UserID *int `json:"user_id,omitempty" url:"user_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InternalAccountsInternalWebUserSecretResponse) GetCreatedAt() *int {
	if i == nil {
		return nil
	}
	return i.CreatedAt
}

func (i *InternalAccountsInternalWebUserSecretResponse) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *InternalAccountsInternalWebUserSecretResponse) GetKey() *string {
	if i == nil {
		return nil
	}
	return i.Key
}

func (i *InternalAccountsInternalWebUserSecretResponse) GetUpdatedAt() *int {
	if i == nil {
		return nil
	}
	return i.UpdatedAt
}

func (i *InternalAccountsInternalWebUserSecretResponse) GetUserID() *int {
	if i == nil {
		return nil
	}
	return i.UserID
}

func (i *InternalAccountsInternalWebUserSecretResponse) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InternalAccountsInternalWebUserSecretResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebUserSecretResponse) SetCreatedAt(createdAt *int) {
	i.CreatedAt = createdAt
	i.require(internalAccountsInternalWebUserSecretResponseFieldCreatedAt)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebUserSecretResponse) SetDescription(description *string) {
	i.Description = description
	i.require(internalAccountsInternalWebUserSecretResponseFieldDescription)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebUserSecretResponse) SetKey(key *string) {
	i.Key = key
	i.require(internalAccountsInternalWebUserSecretResponseFieldKey)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebUserSecretResponse) SetUpdatedAt(updatedAt *int) {
	i.UpdatedAt = updatedAt
	i.require(internalAccountsInternalWebUserSecretResponseFieldUpdatedAt)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebUserSecretResponse) SetUserID(userID *int) {
	i.UserID = userID
	i.require(internalAccountsInternalWebUserSecretResponseFieldUserID)
}

func (i *InternalAccountsInternalWebUserSecretResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler InternalAccountsInternalWebUserSecretResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InternalAccountsInternalWebUserSecretResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InternalAccountsInternalWebUserSecretResponse) MarshalJSON() ([]byte, error) {
	type embed InternalAccountsInternalWebUserSecretResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InternalAccountsInternalWebUserSecretResponse) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// User secret metadata including the decrypted value.
var (
	internalAccountsInternalWebUserSecretValueResponseFieldCreatedAt   = big.NewInt(1 << 0)
	internalAccountsInternalWebUserSecretValueResponseFieldDescription = big.NewInt(1 << 1)
	internalAccountsInternalWebUserSecretValueResponseFieldKey         = big.NewInt(1 << 2)
	internalAccountsInternalWebUserSecretValueResponseFieldUpdatedAt   = big.NewInt(1 << 3)
	internalAccountsInternalWebUserSecretValueResponseFieldUserID      = big.NewInt(1 << 4)
	internalAccountsInternalWebUserSecretValueResponseFieldValue       = big.NewInt(1 << 5)
)

type InternalAccountsInternalWebUserSecretValueResponse struct {
	// CreatedAt is the Unix timestamp of when the secret was created.
	CreatedAt *int `json:"created_at,omitempty" url:"created_at,omitempty"`
	// Description is a human-readable description of the secret.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Key is the unique key identifying this secret within the user's namespace.
	Key *string `json:"key,omitempty" url:"key,omitempty"`
	// UpdatedAt is the Unix timestamp of when the secret was last updated.
	UpdatedAt *int `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	// UserID is the ID of the user who owns this secret.
	UserID *int `json:"user_id,omitempty" url:"user_id,omitempty"`
	// Value is the decrypted secret value.
	Value *string `json:"value,omitempty" url:"value,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InternalAccountsInternalWebUserSecretValueResponse) GetCreatedAt() *int {
	if i == nil {
		return nil
	}
	return i.CreatedAt
}

func (i *InternalAccountsInternalWebUserSecretValueResponse) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *InternalAccountsInternalWebUserSecretValueResponse) GetKey() *string {
	if i == nil {
		return nil
	}
	return i.Key
}

func (i *InternalAccountsInternalWebUserSecretValueResponse) GetUpdatedAt() *int {
	if i == nil {
		return nil
	}
	return i.UpdatedAt
}

func (i *InternalAccountsInternalWebUserSecretValueResponse) GetUserID() *int {
	if i == nil {
		return nil
	}
	return i.UserID
}

func (i *InternalAccountsInternalWebUserSecretValueResponse) GetValue() *string {
	if i == nil {
		return nil
	}
	return i.Value
}

func (i *InternalAccountsInternalWebUserSecretValueResponse) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InternalAccountsInternalWebUserSecretValueResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebUserSecretValueResponse) SetCreatedAt(createdAt *int) {
	i.CreatedAt = createdAt
	i.require(internalAccountsInternalWebUserSecretValueResponseFieldCreatedAt)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebUserSecretValueResponse) SetDescription(description *string) {
	i.Description = description
	i.require(internalAccountsInternalWebUserSecretValueResponseFieldDescription)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebUserSecretValueResponse) SetKey(key *string) {
	i.Key = key
	i.require(internalAccountsInternalWebUserSecretValueResponseFieldKey)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebUserSecretValueResponse) SetUpdatedAt(updatedAt *int) {
	i.UpdatedAt = updatedAt
	i.require(internalAccountsInternalWebUserSecretValueResponseFieldUpdatedAt)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebUserSecretValueResponse) SetUserID(userID *int) {
	i.UserID = userID
	i.require(internalAccountsInternalWebUserSecretValueResponseFieldUserID)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalAccountsInternalWebUserSecretValueResponse) SetValue(value *string) {
	i.Value = value
	i.require(internalAccountsInternalWebUserSecretValueResponseFieldValue)
}

func (i *InternalAccountsInternalWebUserSecretValueResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler InternalAccountsInternalWebUserSecretValueResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InternalAccountsInternalWebUserSecretValueResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InternalAccountsInternalWebUserSecretValueResponse) MarshalJSON() ([]byte, error) {
	type embed InternalAccountsInternalWebUserSecretValueResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InternalAccountsInternalWebUserSecretValueResponse) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type PutSecretsUserIDKeyRequestBody struct {
	StringUnknownMap map[string]any
	// Secret value and description
	InternalAccountsInternalWebUpsertSecretReq *InternalAccountsInternalWebUpsertSecretReq

	typ string
}

func (p *PutSecretsUserIDKeyRequestBody) GetStringUnknownMap() map[string]any {
	if p == nil {
		return nil
	}
	return p.StringUnknownMap
}

func (p *PutSecretsUserIDKeyRequestBody) GetInternalAccountsInternalWebUpsertSecretReq() *InternalAccountsInternalWebUpsertSecretReq {
	if p == nil {
		return nil
	}
	return p.InternalAccountsInternalWebUpsertSecretReq
}

func (p *PutSecretsUserIDKeyRequestBody) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMap map[string]any
	if err := json.Unmarshal(data, &valueStringUnknownMap); err == nil {
		p.typ = "StringUnknownMap"
		p.StringUnknownMap = valueStringUnknownMap
		return nil
	}
	valueInternalAccountsInternalWebUpsertSecretReq := new(InternalAccountsInternalWebUpsertSecretReq)
	if err := json.Unmarshal(data, &valueInternalAccountsInternalWebUpsertSecretReq); err == nil {
		p.typ = "InternalAccountsInternalWebUpsertSecretReq"
		p.InternalAccountsInternalWebUpsertSecretReq = valueInternalAccountsInternalWebUpsertSecretReq
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, p)
}

func (p PutSecretsUserIDKeyRequestBody) MarshalJSON() ([]byte, error) {
	if p.typ == "StringUnknownMap" || p.StringUnknownMap != nil {
		return json.Marshal(p.StringUnknownMap)
	}
	if p.typ == "InternalAccountsInternalWebUpsertSecretReq" || p.InternalAccountsInternalWebUpsertSecretReq != nil {
		return json.Marshal(p.InternalAccountsInternalWebUpsertSecretReq)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", p)
}

type PutSecretsUserIDKeyRequestBodyVisitor interface {
	VisitStringUnknownMap(map[string]any) error
	VisitInternalAccountsInternalWebUpsertSecretReq(*InternalAccountsInternalWebUpsertSecretReq) error
}

func (p *PutSecretsUserIDKeyRequestBody) Accept(visitor PutSecretsUserIDKeyRequestBodyVisitor) error {
	if p.typ == "StringUnknownMap" || p.StringUnknownMap != nil {
		return visitor.VisitStringUnknownMap(p.StringUnknownMap)
	}
	if p.typ == "InternalAccountsInternalWebUpsertSecretReq" || p.InternalAccountsInternalWebUpsertSecretReq != nil {
		return visitor.VisitInternalAccountsInternalWebUpsertSecretReq(p.InternalAccountsInternalWebUpsertSecretReq)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", p)
}
