// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersGetWisdomMarketplaceRequest(t *testing.T) {
	t.Run("SetSearch", func(t *testing.T) {
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValueSearch *string
		obj.SetSearch(fernTestValueSearch)
		assert.Equal(t, fernTestValueSearch, obj.Search)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMinPrice", func(t *testing.T) {
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValueMinPrice *float64
		obj.SetMinPrice(fernTestValueMinPrice)
		assert.Equal(t, fernTestValueMinPrice, obj.MinPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMaxPrice", func(t *testing.T) {
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValueMaxPrice *float64
		obj.SetMaxPrice(fernTestValueMaxPrice)
		assert.Equal(t, fernTestValueMaxPrice, obj.MaxPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSort", func(t *testing.T) {
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValueSort *string
		obj.SetSort(fernTestValueSort)
		assert.Equal(t, fernTestValueSort, obj.Sort)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrder", func(t *testing.T) {
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValueOrder *string
		obj.SetOrder(fernTestValueOrder)
		assert.Equal(t, fernTestValueOrder, obj.Order)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLimit", func(t *testing.T) {
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValueLimit *int
		obj.SetLimit(fernTestValueLimit)
		assert.Equal(t, fernTestValueLimit, obj.Limit)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetWisdomMarketplaceRequest(t *testing.T) {
	t.Run("SetSearch_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValueSearch *string

		// Act
		obj.SetSearch(fernTestValueSearch)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMinPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValueMinPrice *float64

		// Act
		obj.SetMinPrice(fernTestValueMinPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMaxPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValueMaxPrice *float64

		// Act
		obj.SetMaxPrice(fernTestValueMaxPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSort_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValueSort *string

		// Act
		obj.SetSort(fernTestValueSort)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrder_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValueOrder *string

		// Act
		obj.SetOrder(fernTestValueOrder)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetWisdomMarketplaceRequest{}
		var fernTestValueLimit *int

		// Act
		obj.SetLimit(fernTestValueLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse(t *testing.T) {
	t.Run("SetCode", func(t *testing.T) {
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueCode *int
		obj.SetCode(fernTestValueCode)
		assert.Equal(t, fernTestValueCode, obj.Code)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetData", func(t *testing.T) {
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueData *InternalWisdomInternalWebMarketplaceListResponse
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLimit", func(t *testing.T) {
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueLimit *int
		obj.SetLimit(fernTestValueLimit)
		assert.Equal(t, fernTestValueLimit, obj.Limit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMessage", func(t *testing.T) {
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueMessage *string
		obj.SetMessage(fernTestValueMessage)
		assert.Equal(t, fernTestValueMessage, obj.Message)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTotal", func(t *testing.T) {
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueTotal *int
		obj.SetTotal(fernTestValueTotal)
		assert.Equal(t, fernTestValueTotal, obj.Total)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserMessage", func(t *testing.T) {
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueUserMessage *string
		obj.SetUserMessage(fernTestValueUserMessage)
		assert.Equal(t, fernTestValueUserMessage, obj.UserMessage)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse(t *testing.T) {
	t.Run("GetCode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var expected *int
		obj.Code = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCode(), "getter should return the property value")
	})

	t.Run("GetCode_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		obj.Code = nil

		// Act & Assert
		assert.Nil(t, obj.GetCode(), "getter should return nil when property is nil")
	})

	t.Run("GetCode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCode() // Should return zero value
	})

	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var expected *InternalWisdomInternalWebMarketplaceListResponse
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

	t.Run("GetLimit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var expected *int
		obj.Limit = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLimit(), "getter should return the property value")
	})

	t.Run("GetLimit_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		obj.Limit = nil

		// Act & Assert
		assert.Nil(t, obj.GetLimit(), "getter should return nil when property is nil")
	})

	t.Run("GetLimit_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLimit() // Should return zero value
	})

	t.Run("GetMessage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var expected *string
		obj.Message = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMessage(), "getter should return the property value")
	})

	t.Run("GetMessage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		obj.Message = nil

		// Act & Assert
		assert.Nil(t, obj.GetMessage(), "getter should return nil when property is nil")
	})

	t.Run("GetMessage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMessage() // Should return zero value
	})

	t.Run("GetPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var expected *int
		obj.Page = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPage(), "getter should return the property value")
	})

	t.Run("GetPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		obj.Page = nil

		// Act & Assert
		assert.Nil(t, obj.GetPage(), "getter should return nil when property is nil")
	})

	t.Run("GetPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPage() // Should return zero value
	})

	t.Run("GetTotal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var expected *int
		obj.Total = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTotal(), "getter should return the property value")
	})

	t.Run("GetTotal_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		obj.Total = nil

		// Act & Assert
		assert.Nil(t, obj.GetTotal(), "getter should return nil when property is nil")
	})

	t.Run("GetTotal_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTotal() // Should return zero value
	})

	t.Run("GetUserMessage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var expected *string
		obj.UserMessage = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUserMessage(), "getter should return the property value")
	})

	t.Run("GetUserMessage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		obj.UserMessage = nil

		// Act & Assert
		assert.Nil(t, obj.GetUserMessage(), "getter should return nil when property is nil")
	})

	t.Run("GetUserMessage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUserMessage() // Should return zero value
	})

}

func TestSettersMarkExplicitGithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse(t *testing.T) {
	t.Run("SetCode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueCode *int

		// Act
		obj.SetCode(fernTestValueCode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueData *InternalWisdomInternalWebMarketplaceListResponse

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueLimit *int

		// Act
		obj.SetLimit(fernTestValueLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMessage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueMessage *string

		// Act
		obj.SetMessage(fernTestValueMessage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTotal_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueTotal *int

		// Act
		obj.SetTotal(fernTestValueTotal)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserMessage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueUserMessage *string

		// Act
		obj.SetUserMessage(fernTestValueUserMessage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersInternalWisdomInternalWebMarketplaceCommunityItem(t *testing.T) {
	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueCreatedAt *int
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDescription", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueDescription *string
		obj.SetDescription(fernTestValueDescription)
		assert.Equal(t, fernTestValueDescription, obj.Description)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueID *int
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLabel", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueLabel *string
		obj.SetLabel(fernTestValueLabel)
		assert.Equal(t, fernTestValueLabel, obj.Label)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMemberCount", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueMemberCount *int
		obj.SetMemberCount(fernTestValueMemberCount)
		assert.Equal(t, fernTestValueMemberCount, obj.MemberCount)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOwnerUserID", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueOwnerUserID *int
		obj.SetOwnerUserID(fernTestValueOwnerUserID)
		assert.Equal(t, fernTestValueOwnerUserID, obj.OwnerUserID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPrice", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValuePrice *float64
		obj.SetPrice(fernTestValuePrice)
		assert.Equal(t, fernTestValuePrice, obj.Price)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPricingModel", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValuePricingModel *string
		obj.SetPricingModel(fernTestValuePricingModel)
		assert.Equal(t, fernTestValuePricingModel, obj.PricingModel)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSlug", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueSlug *string
		obj.SetSlug(fernTestValueSlug)
		assert.Equal(t, fernTestValueSlug, obj.Slug)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersInternalWisdomInternalWebMarketplaceCommunityItem(t *testing.T) {
	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var expected *int
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		obj.CreatedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetCreatedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceCommunityItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetDescription", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var expected *string
		obj.Description = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDescription(), "getter should return the property value")
	})

	t.Run("GetDescription_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		obj.Description = nil

		// Act & Assert
		assert.Nil(t, obj.GetDescription(), "getter should return nil when property is nil")
	})

	t.Run("GetDescription_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceCommunityItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDescription() // Should return zero value
	})

	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var expected *int
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceCommunityItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetLabel", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var expected *string
		obj.Label = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLabel(), "getter should return the property value")
	})

	t.Run("GetLabel_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		obj.Label = nil

		// Act & Assert
		assert.Nil(t, obj.GetLabel(), "getter should return nil when property is nil")
	})

	t.Run("GetLabel_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceCommunityItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLabel() // Should return zero value
	})

	t.Run("GetMemberCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var expected *int
		obj.MemberCount = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMemberCount(), "getter should return the property value")
	})

	t.Run("GetMemberCount_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		obj.MemberCount = nil

		// Act & Assert
		assert.Nil(t, obj.GetMemberCount(), "getter should return nil when property is nil")
	})

	t.Run("GetMemberCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceCommunityItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMemberCount() // Should return zero value
	})

	t.Run("GetOwnerUserID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var expected *int
		obj.OwnerUserID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOwnerUserID(), "getter should return the property value")
	})

	t.Run("GetOwnerUserID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		obj.OwnerUserID = nil

		// Act & Assert
		assert.Nil(t, obj.GetOwnerUserID(), "getter should return nil when property is nil")
	})

	t.Run("GetOwnerUserID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceCommunityItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOwnerUserID() // Should return zero value
	})

	t.Run("GetPrice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var expected *float64
		obj.Price = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPrice(), "getter should return the property value")
	})

	t.Run("GetPrice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		obj.Price = nil

		// Act & Assert
		assert.Nil(t, obj.GetPrice(), "getter should return nil when property is nil")
	})

	t.Run("GetPrice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceCommunityItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPrice() // Should return zero value
	})

	t.Run("GetPricingModel", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var expected *string
		obj.PricingModel = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPricingModel(), "getter should return the property value")
	})

	t.Run("GetPricingModel_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		obj.PricingModel = nil

		// Act & Assert
		assert.Nil(t, obj.GetPricingModel(), "getter should return nil when property is nil")
	})

	t.Run("GetPricingModel_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceCommunityItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPricingModel() // Should return zero value
	})

	t.Run("GetSlug", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var expected *string
		obj.Slug = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSlug(), "getter should return the property value")
	})

	t.Run("GetSlug_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		obj.Slug = nil

		// Act & Assert
		assert.Nil(t, obj.GetSlug(), "getter should return nil when property is nil")
	})

	t.Run("GetSlug_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceCommunityItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSlug() // Should return zero value
	})

}

func TestSettersMarkExplicitInternalWisdomInternalWebMarketplaceCommunityItem(t *testing.T) {
	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueCreatedAt *int

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDescription_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueDescription *string

		// Act
		obj.SetDescription(fernTestValueDescription)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueID *int

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLabel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueLabel *string

		// Act
		obj.SetLabel(fernTestValueLabel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMemberCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueMemberCount *int

		// Act
		obj.SetMemberCount(fernTestValueMemberCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOwnerUserID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueOwnerUserID *int

		// Act
		obj.SetOwnerUserID(fernTestValueOwnerUserID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValuePrice *float64

		// Act
		obj.SetPrice(fernTestValuePrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPricingModel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValuePricingModel *string

		// Act
		obj.SetPricingModel(fernTestValuePricingModel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSlug_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		var fernTestValueSlug *string

		// Act
		obj.SetSlug(fernTestValueSlug)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersInternalWisdomInternalWebMarketplaceListResponse(t *testing.T) {
	t.Run("SetData", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueData []*InternalWisdomInternalWebMarketplaceCommunityItem
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLimit", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueLimit *int
		obj.SetLimit(fernTestValueLimit)
		assert.Equal(t, fernTestValueLimit, obj.Limit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetObject", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueObject *string
		obj.SetObject(fernTestValueObject)
		assert.Equal(t, fernTestValueObject, obj.Object)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTotal", func(t *testing.T) {
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueTotal *int
		obj.SetTotal(fernTestValueTotal)
		assert.Equal(t, fernTestValueTotal, obj.Total)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersInternalWisdomInternalWebMarketplaceListResponse(t *testing.T) {
	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var expected []*InternalWisdomInternalWebMarketplaceCommunityItem
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

	t.Run("GetLimit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var expected *int
		obj.Limit = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLimit(), "getter should return the property value")
	})

	t.Run("GetLimit_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		obj.Limit = nil

		// Act & Assert
		assert.Nil(t, obj.GetLimit(), "getter should return nil when property is nil")
	})

	t.Run("GetLimit_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLimit() // Should return zero value
	})

	t.Run("GetObject", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var expected *string
		obj.Object = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetObject(), "getter should return the property value")
	})

	t.Run("GetObject_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		obj.Object = nil

		// Act & Assert
		assert.Nil(t, obj.GetObject(), "getter should return nil when property is nil")
	})

	t.Run("GetObject_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetObject() // Should return zero value
	})

	t.Run("GetPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var expected *int
		obj.Page = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPage(), "getter should return the property value")
	})

	t.Run("GetPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		obj.Page = nil

		// Act & Assert
		assert.Nil(t, obj.GetPage(), "getter should return nil when property is nil")
	})

	t.Run("GetPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPage() // Should return zero value
	})

	t.Run("GetTotal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var expected *int
		obj.Total = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTotal(), "getter should return the property value")
	})

	t.Run("GetTotal_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		obj.Total = nil

		// Act & Assert
		assert.Nil(t, obj.GetTotal(), "getter should return nil when property is nil")
	})

	t.Run("GetTotal_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTotal() // Should return zero value
	})

}

func TestSettersMarkExplicitInternalWisdomInternalWebMarketplaceListResponse(t *testing.T) {
	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueData []*InternalWisdomInternalWebMarketplaceCommunityItem

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueLimit *int

		// Act
		obj.SetLimit(fernTestValueLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetObject_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueObject *string

		// Act
		obj.SetObject(fernTestValueObject)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTotal_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		var fernTestValueTotal *int

		// Act
		obj.SetTotal(fernTestValueTotal)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingGithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingInternalWisdomInternalWebMarketplaceCommunityItem(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled InternalWisdomInternalWebMarketplaceCommunityItem
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj InternalWisdomInternalWebMarketplaceCommunityItem
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj InternalWisdomInternalWebMarketplaceCommunityItem
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingInternalWisdomInternalWebMarketplaceListResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled InternalWisdomInternalWebMarketplaceListResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj InternalWisdomInternalWebMarketplaceListResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj InternalWisdomInternalWebMarketplaceListResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringGithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringInternalWisdomInternalWebMarketplaceCommunityItem(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceCommunityItem
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringInternalWisdomInternalWebMarketplaceListResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceListResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesGithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebMarketplaceListResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesInternalWisdomInternalWebMarketplaceCommunityItem(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &InternalWisdomInternalWebMarketplaceCommunityItem{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceCommunityItem
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesInternalWisdomInternalWebMarketplaceListResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &InternalWisdomInternalWebMarketplaceListResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InternalWisdomInternalWebMarketplaceListResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
