// Code generated by Fern. DO NOT EDIT.

package gateway

import (
	context "context"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	core "github.com/MKT-AGI/mkt-sdk-go/core"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Sends a "say hi" prompt to the specified provider+model and returns the response.
func (c *Client) TestModelConnectivity(
	ctx context.Context,
	request *mktsdkgo.PostGatewayUserIDTestModelRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebTestModelResponse, error) {
	response, err := c.WithRawResponse.TestModelConnectivity(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns paginated request logs for the current user.
func (c *Client) ListRequestLogs(
	ctx context.Context,
	request *mktsdkgo.GetGatewayLogsRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebListLogsResponse, error) {
	response, err := c.WithRawResponse.ListRequestLogs(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns models that the current authenticated user (via cookie or API key) is allowed to see.
func (c *Client) ListModelsVisibleToCurrentPrincipal(
	ctx context.Context,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultAny, error) {
	response, err := c.WithRawResponse.ListModelsVisibleToCurrentPrincipal(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns revenue summary for all models owned by the current user.
func (c *Client) SellerRevenueSummary(
	ctx context.Context,
	request *mktsdkgo.GetGatewaySellerRevenueRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebSellerRevenueResponse, error) {
	response, err := c.WithRawResponse.SellerRevenueSummary(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns paginated daily usage records for the current user.
func (c *Client) ListUsageRecords(
	ctx context.Context,
	request *mktsdkgo.GetGatewayUsageRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebListUsageResponse, error) {
	response, err := c.WithRawResponse.ListUsageRecords(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
