// Code generated by Fern. DO NOT EDIT.

package payments

import (
	context "context"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	core "github.com/MKT-AGI/mkt-sdk-go/core"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// List all payment orders for the authenticated user with pagination
func (c *Client) ListPaymentOrders(
	ctx context.Context,
	request *mktsdkgo.GetAPIV1PaymentOrdersRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.ListPaymentOrders(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Create a new top-up payment order with an optional product
func (c *Client) CreatePaymentOrder(
	ctx context.Context,
	request *mktsdkgo.PostAPIV1PaymentOrdersRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.CreatePaymentOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Retrieve a payment order by ID for the authenticated user
func (c *Client) GetPaymentOrder(
	ctx context.Context,
	request *mktsdkgo.GetAPIV1PaymentOrdersIDRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.GetPaymentOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
