// Code generated by Fern. DO NOT EDIT.

package wisdompublic

import (
	context "context"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	core "github.com/MKT-AGI/mkt-sdk-go/core"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// List public content nodes without authentication
func (c *Client) ListPublicContents(
	ctx context.Context,
	request *mktsdkgo.GetPublicWisdomRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.ListPublicContents(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
