// Code generated by Fern. DO NOT EDIT.

package auth_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	client "github.com/MKT-AGI/mkt-sdk-go/client"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAuthGenerateImageCaptchaWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Auth.GenerateImageCaptcha(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthGenerateImageCaptchaWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthGenerateImageCaptchaWithWireMock", "GET", "/auth/captcha", nil, 1)
}

func TestAuthSendEmailVerificationCodeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.PostAuthEmailSendRequest{
		StringUnknownMap: map[string]any{
			"key": "value",
		},
	}
	invocationErr := client.Auth.SendEmailVerificationCode(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthSendEmailVerificationCodeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthSendEmailVerificationCodeWithWireMock", "POST", "/auth/email/send", nil, 1)
}

func TestAuthVerifyEmailCodeAndAuthenticateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.PostAuthEmailVerifyRequest{
		StringUnknownMap: map[string]any{
			"key": "value",
		},
	}
	_, invocationErr := client.Auth.VerifyEmailCodeAndAuthenticate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthVerifyEmailCodeAndAuthenticateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthVerifyEmailCodeAndAuthenticateWithWireMock", "POST", "/auth/email/verify", nil, 1)
}

func TestAuthExchangeGitHubCodeForTokensAPIWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.PostAuthGithubRequest{
		StringUnknownMap: map[string]any{
			"key": "value",
		},
	}
	invocationErr := client.Auth.ExchangeGitHubCodeForTokensAPI(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthExchangeGitHubCodeForTokensAPIWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthExchangeGitHubCodeForTokensAPIWithWireMock", "POST", "/auth/github", nil, 1)
}

func TestAuthGitHubOAuthCallbackWebWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.GetAuthGithubCallbackRequest{
		State: "state",
		Code:  "code",
	}
	invocationErr := client.Auth.GitHubOAuthCallbackWeb(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthGitHubOAuthCallbackWebWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthGitHubOAuthCallbackWebWithWireMock", "GET", "/auth/github/callback", map[string]interface{}{"state": "state", "code": "code"}, 1)
}

func TestAuthInitiateGitHubOAuthWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.GetAuthGithubLoginRequest{
		RefURI: "ref_uri",
	}
	invocationErr := client.Auth.InitiateGitHubOAuth(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthInitiateGitHubOAuthWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthInitiateGitHubOAuthWithWireMock", "GET", "/auth/github/login", map[string]interface{}{"ref_uri": "ref_uri"}, 1)
}

func TestAuthExchangeGoogleCodeForTokensAPIWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.PostAuthGoogleRequest{
		StringUnknownMap: map[string]any{
			"key": "value",
		},
	}
	invocationErr := client.Auth.ExchangeGoogleCodeForTokensAPI(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthExchangeGoogleCodeForTokensAPIWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthExchangeGoogleCodeForTokensAPIWithWireMock", "POST", "/auth/google", nil, 1)
}

func TestAuthGoogleOAuthCallbackWebWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.GetAuthGoogleCallbackRequest{
		State: "state",
		Code:  "code",
	}
	invocationErr := client.Auth.GoogleOAuthCallbackWeb(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthGoogleOAuthCallbackWebWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthGoogleOAuthCallbackWebWithWireMock", "GET", "/auth/google/callback", map[string]interface{}{"state": "state", "code": "code"}, 1)
}

func TestAuthInitiateGoogleOAuthWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.GetAuthGoogleLoginRequest{
		RefURI: "ref_uri",
	}
	invocationErr := client.Auth.InitiateGoogleOAuth(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthInitiateGoogleOAuthWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthInitiateGoogleOAuthWithWireMock", "GET", "/auth/google/login", map[string]interface{}{"ref_uri": "ref_uri"}, 1)
}

func TestAuthLogoutCurrentUserWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	invocationErr := client.Auth.LogoutCurrentUser(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthLogoutCurrentUserWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthLogoutCurrentUserWithWireMock", "POST", "/auth/logout", nil, 1)
}

func TestAuthSendSmsVerificationCodeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.PostAuthSmsSendRequest{
		StringUnknownMap: map[string]any{
			"key": "value",
		},
	}
	invocationErr := client.Auth.SendSmsVerificationCode(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthSendSmsVerificationCodeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthSendSmsVerificationCodeWithWireMock", "POST", "/auth/sms/send", nil, 1)
}

func TestAuthVerifySmsCodeAndAuthenticateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &mktsdkgo.PostAuthSmsVerifyRequest{
		StringUnknownMap: map[string]any{
			"key": "value",
		},
	}
	_, invocationErr := client.Auth.VerifySmsCodeAndAuthenticate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthVerifySmsCodeAndAuthenticateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthVerifySmsCodeAndAuthenticateWithWireMock", "POST", "/auth/sms/verify", nil, 1)
}
