// Code generated by Fern. DO NOT EDIT.

package sessions

import (
	context "context"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	core "github.com/MKT-AGI/mkt-sdk-go/core"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Return paginated list of AI chat sessions for the current user
func (c *Client) ListAiSessions(
	ctx context.Context,
	request *mktsdkgo.GetGatewaySessionsRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalAigatewayInternalDomainAiSession, error) {
	response, err := c.WithRawResponse.ListAiSessions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new AI chat session for the current user
func (c *Client) CreateAiSession(
	ctx context.Context,
	request *mktsdkgo.PostGatewaySessionsRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalAigatewayInternalDomainAiSession, error) {
	response, err := c.WithRawResponse.CreateAiSession(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Soft-delete an AI chat session
func (c *Client) DeleteAiSession(
	ctx context.Context,
	request *mktsdkgo.DeleteGatewaySessionsIDRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultAny, error) {
	response, err := c.WithRawResponse.DeleteAiSession(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update session title or metadata
func (c *Client) UpdateAiSession(
	ctx context.Context,
	request *mktsdkgo.PatchGatewaySessionsIDRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultAny, error) {
	response, err := c.WithRawResponse.UpdateAiSession(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
