// Code generated by Fern. DO NOT EDIT.

package devices

import (
	context "context"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	core "github.com/MKT-AGI/mkt-sdk-go/core"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Register a push notification device for the current user
func (c *Client) RegisterDevice(
	ctx context.Context,
	request *mktsdkgo.PostMessagingDevicesRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.RegisterDevice(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Unregister a push notification device
func (c *Client) UnregisterDevice(
	ctx context.Context,
	request *mktsdkgo.DeleteMessagingDevicesDeviceIDRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.UnregisterDevice(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
