// Code generated by Fern. DO NOT EDIT.

package usermodels

import (
	context "context"
	http "net/http"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	core "github.com/MKT-AGI/mkt-sdk-go/core"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListModelVisibilityFilters(
	ctx context.Context,
	request *mktsdkgo.GetGatewayUserIDModelsIDFiltersRequest,
	opts ...option.RequestOption,
) (*core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultArrayUint], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/gateway/%v/models/%v/filters",
		request.UserID,
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultArrayUint
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultArrayUint]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) AddModelVisibilityFilter(
	ctx context.Context,
	request *mktsdkgo.PostGatewayUserIDModelsIDFiltersRequest,
	opts ...option.RequestOption,
) (*core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultAny], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/gateway/%v/models/%v/filters",
		request.UserID,
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultAny
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultAny]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) RemoveModelVisibilityFilter(
	ctx context.Context,
	request *mktsdkgo.DeleteGatewayUserIDModelsIDFiltersTargetUserIDRequest,
	opts ...option.RequestOption,
) (*core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultAny], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/gateway/%v/models/%v/filters/%v",
		request.UserID,
		request.ID,
		request.TargetUserID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultAny
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultAny]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
