// Code generated by Fern. DO NOT EDIT.

package iam

import (
	context "context"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	core "github.com/MKT-AGI/mkt-sdk-go/core"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// List API key metadata for the authenticated user. Raw keys and hashes are never returned.
func (c *Client) ListAPIKeys(
	ctx context.Context,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebAPIKeyResponse, error) {
	response, err := c.WithRawResponse.ListAPIKeys(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create an API key for the authenticated user. The raw API key is returned only once in this response.
func (c *Client) CreateAPIKey(
	ctx context.Context,
	request *mktsdkgo.PostIamAPIKeysRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateAPIKeyResponse, error) {
	response, err := c.WithRawResponse.CreateAPIKey(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Revoke an API key owned by the authenticated user.
func (c *Client) RevokeAPIKey(
	ctx context.Context,
	request *mktsdkgo.DeleteIamAPIKeysIDRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.RevokeAPIKey(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// 列出资源的可见性过滤器用户列表。返回被添加到可见性白名单中的用户 ID。
func (c *Client) ListVisibilityFilters(
	ctx context.Context,
	request *mktsdkgo.GetIamVisibilityFiltersRequest,
	opts ...option.RequestOption,
) (*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultArrayUint, error) {
	response, err := c.WithRawResponse.ListVisibilityFilters(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// 添加可见性过滤器，将指定用户添加到资源的可见性白名单中。
func (c *Client) AddVisibilityFilter(
	ctx context.Context,
	request *mktsdkgo.PostIamVisibilityFiltersRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.AddVisibilityFilter(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// 移除可见性过滤器，将指定用户从资源的可见性白名单中移除。
func (c *Client) RemoveVisibilityFilter(
	ctx context.Context,
	request *mktsdkgo.DeleteIamVisibilityFiltersResourceTypeResourceIDUserIDRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.RemoveVisibilityFilter(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
