// Code generated by Fern. DO NOT EDIT.

package files_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	client "github.com/MKT-AGI/mkt-sdk-go/client"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestFilesListFilesInDirectoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.GetAdminFilesRequest{}
	_, invocationErr := client.Files.ListFilesInDirectory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFilesListFilesInDirectoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFilesListFilesInDirectoryWithWireMock", "GET", "/admin/files", nil, 1)
}

func TestFilesGetFileWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.GetAdminFilesIDRequest{
		ID: 1,
	}
	_, invocationErr := client.Files.GetFile(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFilesGetFileWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFilesGetFileWithWireMock", "GET", "/admin/files/1", nil, 1)
}

func TestFilesDeleteFileWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.DeleteAdminFilesIDRequest{
		ID: 1,
	}
	_, invocationErr := client.Files.DeleteFile(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFilesDeleteFileWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFilesDeleteFileWithWireMock", "DELETE", "/admin/files/1", nil, 1)
}

func TestFilesUpdateFileWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.PatchAdminFilesIDRequest{
		ID: 1,
		Body: &mktsdkgo.PatchAdminFilesIDRequestBody{
			StringUnknownMap: map[string]any{
				"key": "value",
			},
		},
	}
	_, invocationErr := client.Files.UpdateFile(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFilesUpdateFileWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFilesUpdateFileWithWireMock", "PATCH", "/admin/files/1", nil, 1)
}

func TestFilesGetDownloadURLWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.GetAdminFilesIDDownloadRequest{
		ID: 1,
	}
	_, invocationErr := client.Files.GetDownloadURL(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFilesGetDownloadURLWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFilesGetDownloadURLWithWireMock", "GET", "/admin/files/1/download", nil, 1)
}

func TestFilesIngestFileFromURLWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.PostAdminFilesIngestURLRequest{
		StringUnknownMap: map[string]any{
			"key": "value",
		},
	}
	_, invocationErr := client.Files.IngestFileFromURL(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFilesIngestFileFromURLWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFilesIngestFileFromURLWithWireMock", "POST", "/admin/files/ingest-url", nil, 1)
}
