// Code generated by Fern. DO NOT EDIT.

package wisdomcommunity

import (
	context "context"
	http "net/http"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	core "github.com/MKT-AGI/mkt-sdk-go/core"
	internal "github.com/MKT-AGI/mkt-sdk-go/internal"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListCommunities(
	ctx context.Context,
	request *mktsdkgo.GetWisdomCommunityRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := baseURL + "/wisdom/community"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) CreateCommunity(
	ctx context.Context,
	request *mktsdkgo.PostWisdomCommunityRequest,
	opts ...option.RequestOption,
) (*core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebCommunityResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := baseURL + "/wisdom/community"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebCommunityResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebCommunityResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetCommunity(
	ctx context.Context,
	request *mktsdkgo.GetWisdomCommunityIDRequest,
	opts ...option.RequestOption,
) (*core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebCommunityResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/wisdom/community/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebCommunityResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebCommunityResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteCommunity(
	ctx context.Context,
	request *mktsdkgo.DeleteWisdomCommunityIDRequest,
	opts ...option.RequestOption,
) (*core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/wisdom/community/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdateCommunity(
	ctx context.Context,
	request *mktsdkgo.PatchWisdomCommunityIDRequest,
	opts ...option.RequestOption,
) (*core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebCommunityResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/wisdom/community/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebCommunityResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebCommunityResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) SetCommunityPricing(
	ctx context.Context,
	request *mktsdkgo.PutWisdomCommunityIDPricingRequest,
	opts ...option.RequestOption,
) (*core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebCommunityResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/wisdom/community/%v/pricing",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebCommunityResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebCommunityResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PurchaseCommunity(
	ctx context.Context,
	request *mktsdkgo.PostWisdomCommunityIDPurchaseRequest,
	opts ...option.RequestOption,
) (*core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultMapStringString], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:8080/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/wisdom/community/%v/purchase",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultMapStringString
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mktsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mktsdkgo.GithubComMktAgiAixInternalPkgGinxResultMapStringString]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
