// Code generated by Fern. DO NOT EDIT.

package wallets_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	mktsdkgo "github.com/MKT-AGI/mkt-sdk-go"
	client "github.com/MKT-AGI/mkt-sdk-go/client"
	option "github.com/MKT-AGI/mkt-sdk-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestWalletsGetTransferDetailWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.GetAPIV1PaymentWalletTransfersTransferNoRequest{
		TransferNo: 1,
	}
	_, invocationErr := client.Wallets.GetTransferDetail(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWalletsGetTransferDetailWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWalletsGetTransferDetailWithWireMock", "GET", "/api/v1/payment/wallet/transfers/1", nil, 1)
}

func TestWalletsListWalletsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	_, invocationErr := client.Wallets.ListWallets(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWalletsListWalletsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWalletsListWalletsWithWireMock", "GET", "/api/v1/payment/wallets", nil, 1)
}

func TestWalletsGetWalletWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.GetAPIV1PaymentWalletsIDRequest{
		ID: 1,
	}
	_, invocationErr := client.Wallets.GetWallet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWalletsGetWalletWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWalletsGetWalletWithWireMock", "GET", "/api/v1/payment/wallets/1", nil, 1)
}

func TestWalletsConvertWalletCurrencyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.PostAPIV1PaymentWalletsIDConvertCurrencyRequest{
		ID: 1,
		Body: &mktsdkgo.PostAPIV1PaymentWalletsIDConvertCurrencyRequestBody{
			StringUnknownMap: map[string]any{
				"key": "value",
			},
		},
	}
	invocationErr := client.Wallets.ConvertWalletCurrency(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWalletsConvertWalletCurrencyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWalletsConvertWalletCurrencyWithWireMock", "POST", "/api/v1/payment/wallets/1/convert-currency", nil, 1)
}

func TestWalletsListWalletTransactionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.GetAPIV1PaymentWalletsIDTransactionsRequest{
		ID: 1,
	}
	invocationErr := client.Wallets.ListWalletTransactions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWalletsListWalletTransactionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWalletsListWalletTransactionsWithWireMock", "GET", "/api/v1/payment/wallets/1/transactions", nil, 1)
}

func TestWalletsTransferBetweenWalletsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.PostAPIV1PaymentWalletsIDTransferRequest{
		ID: 1,
		Body: &mktsdkgo.PostAPIV1PaymentWalletsIDTransferRequestBody{
			StringUnknownMap: map[string]any{
				"key": "value",
			},
		},
	}
	_, invocationErr := client.Wallets.TransferBetweenWallets(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWalletsTransferBetweenWalletsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWalletsTransferBetweenWalletsWithWireMock", "POST", "/api/v1/payment/wallets/1/transfer", nil, 1)
}

func TestWalletsTransferRevenueWalletBalanceToMainWalletWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &mktsdkgo.PostAPIV1PaymentWalletsIDTransferToMainRequest{
		ID: 1,
		Body: &mktsdkgo.PostAPIV1PaymentWalletsIDTransferToMainRequestBody{
			StringUnknownMap: map[string]any{
				"key": "value",
			},
		},
	}
	_, invocationErr := client.Wallets.TransferRevenueWalletBalanceToMainWallet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWalletsTransferRevenueWalletBalanceToMainWalletWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWalletsTransferRevenueWalletBalanceToMainWalletWithWireMock", "POST", "/api/v1/payment/wallets/1/transfer-to-main", nil, 1)
}
